# Writes OUTPUT, a TU defining orpheus_build_stamp(). Run as `cmake -P` on every build, it
# rewrites the file only when the key below changes, so a no-op build doesn't relink.
# Inputs: SOURCE_DIR (liborpheus_dsp), OUTPUT, CONFIG, WITH_GRIDS.

set(rev "nogit")
set(dirty "")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(rc EQUAL 0)
        set(rev "${out}")
        # Scoped to liborpheus_dsp: edits elsewhere in the repo don't change the library.
        execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain -- .
            WORKING_DIRECTORY "${SOURCE_DIR}"
            OUTPUT_VARIABLE out ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(out)
            set(dirty "-dirty")
        endif()
    endif()
endif()

# Newest mtime across the sources that end up in a shipped binary. Build dirs live under
# desktop/ and platform/, so those two are matched non-recursively.
file(GLOB_RECURSE inputs LIST_DIRECTORIES false
    "${SOURCE_DIR}/src/*" "${SOURCE_DIR}/include/*")
file(GLOB more LIST_DIRECTORIES false
    "${SOURCE_DIR}/desktop/*.cpp" "${SOURCE_DIR}/desktop/*.h" "${SOURCE_DIR}/desktop/*.mm"
    "${SOURCE_DIR}/CMakeLists.txt")
list(APPEND inputs ${more})
set(newest_secs 0)
set(newest_file "")
foreach(f IN LISTS inputs)
    file(TIMESTAMP "${f}" secs "%s")
    if(secs GREATER newest_secs)
        set(newest_secs ${secs})
        set(newest_file "${f}")
    endif()
endforeach()
file(TIMESTAMP "${newest_file}" newest_iso "%Y-%m-%dT%H:%M:%S")
get_filename_component(newest_name "${newest_file}" NAME)

set(key "git=${rev}${dirty} src=${newest_iso}(${newest_name}) config=${CONFIG} grids=${WITH_GRIDS}")

if(EXISTS "${OUTPUT}")
    file(STRINGS "${OUTPUT}" old_key LIMIT_COUNT 1 REGEX "^// key: ")
    if(old_key STREQUAL "// key: ${key}")
        return()
    endif()
endif()

string(TIMESTAMP built "%Y-%m-%dT%H:%M:%S")
file(WRITE "${OUTPUT}" "// key: ${key}
// Generated by liborpheus_dsp/cmake/build_stamp.cmake on every build. Do not edit.
#include \"orpheus_dsp.h\"

const char* orpheus_build_stamp(void) {
    return \"built=${built} ${key}\";
}
")
