package org.balch.orpheus.features.presets

import kotlinx.serialization.json.Json
import org.balch.orpheus.core.presets.SynthPatch
import org.balch.orpheus.core.presets.SynthPreset
import java.io.File

/**
 * JVM-only CLI that discovers SynthPatch classes, serializes their presets to JSON,
 * and generates a BundledPresets.kt source file for the wasmJsMain source set.
 *
 * Args: <outputDir> <patchesSourceDir>
 */
fun main(args: Array<String>) {
    require(args.size == 2) { "Usage: PresetJsonGenerator <outputDir> <patchesSourceDir>" }
    val outputDir = File(args[0])
    val patchesSourceDir = File(args[1])

    val json = Json { prettyPrint = false }

    // Scan patches source dir for .kt files, derive FQCNs
    val patchFiles = patchesSourceDir.listFiles { f -> f.extension == "kt" } ?: emptyArray()
    val packageName = "org.balch.orpheus.features.presets.patches"

    val entries = patchFiles.mapNotNull { file ->
        val className = file.nameWithoutExtension
        val fqcn = "$packageName.$className"
        try {
            val clazz = Class.forName(fqcn)
            val patch = clazz.getDeclaredConstructor().newInstance() as SynthPatch
            val jsonString = json.encodeToString(SynthPreset.serializer(), patch.preset)
            println("  Serialized: ${patch.name} (${jsonString.length} chars)")
            patch.name to jsonString
        } catch (e: Exception) {
            System.err.println("  Skipped $className: ${e.message}")
            null
        }
    }

    // Generate BundledPresets.kt
    val targetDir = File(outputDir, "org/balch/orpheus/features/presets")
    targetDir.mkdirs()

    val kotlinSource = buildString {
        appendLine("package org.balch.orpheus.features.presets")
        appendLine()
        appendLine("// Generated by PresetJsonGenerator - do not edit manually")
        appendLine("object BundledPresets {")
        appendLine("    val presets: Map<String, String> = mapOf(")
        entries.forEachIndexed { i, (name, jsonStr) ->
            val escapedJson = jsonStr.replace("$", "\${'\$'}")
            val comma = if (i < entries.size - 1) "," else ""
            appendLine("        \"$name\" to \"\"\"$escapedJson\"\"\"$comma")
        }
        appendLine("    )")
        appendLine("}")
    }

    File(targetDir, "BundledPresets.kt").writeText(kotlinSource)
    println("Generated BundledPresets.kt with ${entries.size} presets")
}
