package org.balch.orpheus.features.presets

import kotlinx.coroutines.test.runTest
import org.balch.orpheus.core.plugin.PortValue
import org.balch.orpheus.core.presets.SynthPreset
import org.balch.orpheus.features.presets.patches.CleanPatch
import org.balch.orpheus.features.presets.patches.Funk491Patch
import org.balch.orpheus.features.presets.patches.OrpheusPatch
import org.balch.orpheus.features.presets.patches.PinkPatch
import org.balch.orpheus.features.presets.patches.SixSevenPatch
import org.balch.orpheus.features.presets.patches.SwirlyDreamsPatch
import java.io.File
import kotlin.test.Test

/**
 * Keeps `liborpheus_dsp/test/data/preset_*.h` in sync with the bundled preset JSON.
 *
 * The C++ harness (`test_preset_voices.cpp`) `#include`s these headers to apply exact
 * preset values to the engine, so they must stay a faithful projection of the JSON the
 * app actually ships.
 *
 * By default this only **verifies** — it never writes to the working tree. Regenerate
 * deliberately after changing a preset JSON:
 * ```
 * ./gradlew :features:presets:exportPresets
 * ```
 */
class ExportPresetsTest {

    private val outDir = File("../../liborpheus_dsp/test/data")

    @Test
    fun presetFixturesMatchPresetJson() = runTest {
        syncPreset("pink", PinkPatch().loadPreset())
        syncPreset("clean", CleanPatch().loadPreset())
        syncPreset("six_seven", SixSevenPatch().loadPreset())
        syncPreset("orpheus", OrpheusPatch().loadPreset())
        syncPreset("funk491", Funk491Patch().loadPreset())
        syncPreset("swirly_dreams", SwirlyDreamsPatch().loadPreset())
    }

    private fun syncPreset(id: String, preset: SynthPreset) {
        GeneratedFixture.sync(
            file = File(outDir, "preset_$id.h"),
            generated = renderHeader(id, preset),
            regenerateHint = REGENERATE_HINT,
        )
    }

    private fun renderHeader(id: String, preset: SynthPreset): String {
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by ExportPresetsTest — do not edit")
        sb.appendLine("// Preset: ${preset.name}")
        sb.appendLine("#pragma once")
        sb.appendLine()
        sb.appendLine("#include \"preset_port.h\"")
        sb.appendLine("#include <vector>")
        sb.appendLine()
        sb.appendLine("static const std::vector<PresetPort> preset_${id}_ports = {")

        preset.portValues.entries
            .sortedBy { it.key }
            .forEach { (key, value) ->
                // key format: "org.balch.orpheus.plugins.voice:tune_0"
                val parts = key.split(":", limit = 2)
                if (parts.size == 2) {
                    val uri = parts[0]
                    val symbol = parts[1]
                    when (value) {
                        is PortValue.FloatValue ->
                            sb.appendLine("    {\"$uri\", \"$symbol\", ${value.value}f, false},")
                        is PortValue.IntValue ->
                            sb.appendLine("    {\"$uri\", \"$symbol\", ${value.value}.0f, true},")
                        is PortValue.BoolValue ->
                            sb.appendLine("    {\"$uri\", \"$symbol\", ${if (value.value) 1.0f else 0.0f}f, true},")
                        is PortValue.StringValue ->
                            sb.appendLine("    // STRING: $uri:$symbol = \"${value.value}\"")
                    }
                }
            }

        sb.appendLine("};")
        sb.appendLine()
        sb.appendLine("static const float preset_${id}_bpm = ${preset.bpm}f;")
        return sb.toString()
    }

    private companion object {
        const val REGENERATE_HINT = "./gradlew :features:presets:exportPresets"
    }
}
