package org.balch.orpheus.features.presets

import org.balch.orpheus.core.plugin.PortValue
import org.balch.orpheus.features.presets.patches.CleanPatch
import org.balch.orpheus.features.presets.patches.PinkPatch
import java.io.File
import kotlin.test.Test

/**
 * Exports preset port values as C++ header files for the DSP test harness.
 * Run with:
 *   ./gradlew :features:presets:jvmTest --tests "*ExportPresetsTest*"
 *
 * Generates `liborpheus_dsp/test/data/preset_*.h` files that the C++ tests
 * can #include to apply exact preset values to the engine.
 */
class ExportPresetsTest {

    private val outDir = File("../../liborpheus_dsp/test/data")

    @Test
    fun exportAllPresets() {
        outDir.mkdirs()
        exportPreset("pink", PinkPatch().preset)
        exportPreset("clean", CleanPatch().preset)
    }

    private fun exportPreset(id: String, preset: org.balch.orpheus.core.presets.SynthPreset) {
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by ExportPresetsTest — do not edit")
        sb.appendLine("// Preset: ${preset.name}")
        sb.appendLine("#pragma once")
        sb.appendLine()
        sb.appendLine("#include \"preset_port.h\"")
        sb.appendLine("#include <vector>")
        sb.appendLine()
        sb.appendLine("static const std::vector<PresetPort> preset_${id}_ports = {")

        preset.portValues.entries
            .sortedBy { it.key }
            .forEach { (key, value) ->
                // key format: "org.balch.orpheus.plugins.voice:tune_0"
                val parts = key.split(":", limit = 2)
                if (parts.size == 2) {
                    val uri = parts[0]
                    val symbol = parts[1]
                    when (value) {
                        is PortValue.FloatValue ->
                            sb.appendLine("    {\"$uri\", \"$symbol\", ${value.value}f, false},")
                        is PortValue.IntValue ->
                            sb.appendLine("    {\"$uri\", \"$symbol\", ${value.value}.0f, true},")
                        is PortValue.BoolValue ->
                            sb.appendLine("    {\"$uri\", \"$symbol\", ${if (value.value) 1.0f else 0.0f}f, true},")
                        is PortValue.StringValue ->
                            sb.appendLine("    // STRING: $uri:$symbol = \"${value.value}\"")
                    }
                }
            }

        sb.appendLine("};")
        sb.appendLine()
        sb.appendLine("static const float preset_${id}_bpm = ${preset.bpm}f;")

        val outFile = File(outDir, "preset_$id.h")
        outFile.writeText(sb.toString())
        println("Wrote ${preset.portValues.size} ports to ${outFile.absolutePath}")
    }
}
