#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6144M
# WASM/JS incremental compilation workaround (KT-82395)
kotlin.incremental.js=false
kotlin.incremental.js.klib=false
#Gradle
org.gradle.jvmargs=-Xmx6144M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
#Compose Hot Reload (Experimental)
org.jetbrains.compose.reload.enabled=true
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
compose.desktop.packaging.checkJdkVendor=false