package org.balch.orpheus.core.plugin.symbols

import org.balch.orpheus.core.plugin.PortSymbol
import org.balch.orpheus.core.plugin.Symbol

const val PULSAR_URI = "org.balch.orpheus.plugins.pulsar"

enum class PulsarSymbol(
    override val symbol: Symbol,
    override val uri: String = PULSAR_URI,
    override val displayName: String = symbol.replaceFirstChar { it.uppercase() }
) : PortSymbol {
    PLAYING("playing", displayName = "Playing"),
    VIBE_GENERATION("vibe_generation"),
    ENERGY("energy", displayName = "Energy"),
    COMPLEXITY("complexity", displayName = "Complexity"),
    SPACE("space", displayName = "Space"),
    MOOD("mood", displayName = "Mood"),
    BPM("bpm", displayName = "BPM"),
    DELAY_SEND("delay_send", displayName = "Delay Send"),
    REVERB_SEND("reverb_send", displayName = "Reverb Send"),
    ROOT_NOTE("root_note", displayName = "Root Note"),
    SCALE("scale", displayName = "Scale"),
    MIX("mix", displayName = "Mix"),
    PERC_MIX("perc_mix", displayName = "Percussion Mix"),
    ENVELOPE_MODE("envelope_mode", displayName = "Envelope Mode"),
    SEED("seed"),
    LICK_MUTATION("lick_mutation"),

    // Per-track engine selectors (16 entries)
    TRACK_0_ENGINE_EDM("track_0_engine_edm", displayName = "Track 0 EDM Engine"),
    TRACK_0_ENGINE_SPACE("track_0_engine_space", displayName = "Track 0 Space Engine"),
    TRACK_1_ENGINE_EDM("track_1_engine_edm", displayName = "Track 1 EDM Engine"),
    TRACK_1_ENGINE_SPACE("track_1_engine_space", displayName = "Track 1 Space Engine"),
    TRACK_2_ENGINE_EDM("track_2_engine_edm", displayName = "Track 2 EDM Engine"),
    TRACK_2_ENGINE_SPACE("track_2_engine_space", displayName = "Track 2 Space Engine"),
    TRACK_3_ENGINE_EDM("track_3_engine_edm", displayName = "Track 3 EDM Engine"),
    TRACK_3_ENGINE_SPACE("track_3_engine_space", displayName = "Track 3 Space Engine"),
    TRACK_4_ENGINE_EDM("track_4_engine_edm", displayName = "Track 4 EDM Engine"),
    TRACK_4_ENGINE_SPACE("track_4_engine_space", displayName = "Track 4 Space Engine"),
    TRACK_5_ENGINE_EDM("track_5_engine_edm", displayName = "Track 5 EDM Engine"),
    TRACK_5_ENGINE_SPACE("track_5_engine_space", displayName = "Track 5 Space Engine"),
    TRACK_6_ENGINE_EDM("track_6_engine_edm", displayName = "Track 6 EDM Engine"),
    TRACK_6_ENGINE_SPACE("track_6_engine_space", displayName = "Track 6 Space Engine"),
    TRACK_7_ENGINE_EDM("track_7_engine_edm", displayName = "Track 7 EDM Engine"),
    TRACK_7_ENGINE_SPACE("track_7_engine_space", displayName = "Track 7 Space Engine"),

    // Per-track voice params: VOLUME (8 entries)
    TRACK_0_VOLUME("track_0_volume"),
    TRACK_1_VOLUME("track_1_volume"),
    TRACK_2_VOLUME("track_2_volume"),
    TRACK_3_VOLUME("track_3_volume"),
    TRACK_4_VOLUME("track_4_volume"),
    TRACK_5_VOLUME("track_5_volume"),
    TRACK_6_VOLUME("track_6_volume"),
    TRACK_7_VOLUME("track_7_volume"),

    // Per-track voice params: PAN (8 entries)
    TRACK_0_PAN("track_0_pan"),
    TRACK_1_PAN("track_1_pan"),
    TRACK_2_PAN("track_2_pan"),
    TRACK_3_PAN("track_3_pan"),
    TRACK_4_PAN("track_4_pan"),
    TRACK_5_PAN("track_5_pan"),
    TRACK_6_PAN("track_6_pan"),
    TRACK_7_PAN("track_7_pan"),

    // Per-track voice params: HARMONICS (8 entries)
    TRACK_0_HARMONICS("track_0_harmonics"),
    TRACK_1_HARMONICS("track_1_harmonics"),
    TRACK_2_HARMONICS("track_2_harmonics"),
    TRACK_3_HARMONICS("track_3_harmonics"),
    TRACK_4_HARMONICS("track_4_harmonics"),
    TRACK_5_HARMONICS("track_5_harmonics"),
    TRACK_6_HARMONICS("track_6_harmonics"),
    TRACK_7_HARMONICS("track_7_harmonics"),

    // Per-track voice params: TIMBRE (8 entries)
    TRACK_0_TIMBRE("track_0_timbre"),
    TRACK_1_TIMBRE("track_1_timbre"),
    TRACK_2_TIMBRE("track_2_timbre"),
    TRACK_3_TIMBRE("track_3_timbre"),
    TRACK_4_TIMBRE("track_4_timbre"),
    TRACK_5_TIMBRE("track_5_timbre"),
    TRACK_6_TIMBRE("track_6_timbre"),
    TRACK_7_TIMBRE("track_7_timbre"),

    // Per-track voice params: MORPH (8 entries)
    TRACK_0_MORPH("track_0_morph"),
    TRACK_1_MORPH("track_1_morph"),
    TRACK_2_MORPH("track_2_morph"),
    TRACK_3_MORPH("track_3_morph"),
    TRACK_4_MORPH("track_4_morph"),
    TRACK_5_MORPH("track_5_morph"),
    TRACK_6_MORPH("track_6_morph"),
    TRACK_7_MORPH("track_7_morph"),

    // Per-track voice params: ENVELOPE (8 entries)
    TRACK_0_ENVELOPE("track_0_envelope"),
    TRACK_1_ENVELOPE("track_1_envelope"),
    TRACK_2_ENVELOPE("track_2_envelope"),
    TRACK_3_ENVELOPE("track_3_envelope"),
    TRACK_4_ENVELOPE("track_4_envelope"),
    TRACK_5_ENVELOPE("track_5_envelope"),
    TRACK_6_ENVELOPE("track_6_envelope"),
    TRACK_7_ENVELOPE("track_7_envelope"),

    // Per-track voice params: PERCUSSIVE (8 entries)
    TRACK_0_PERCUSSIVE("track_0_percussive"),
    TRACK_1_PERCUSSIVE("track_1_percussive"),
    TRACK_2_PERCUSSIVE("track_2_percussive"),
    TRACK_3_PERCUSSIVE("track_3_percussive"),
    TRACK_4_PERCUSSIVE("track_4_percussive"),
    TRACK_5_PERCUSSIVE("track_5_percussive"),
    TRACK_6_PERCUSSIVE("track_6_percussive"),
    TRACK_7_PERCUSSIVE("track_7_percussive"),

    // Per-track macro maps: ENERGY_VOL (16 entries per track × 8 tracks = 128)
    TRACK_0_MACRO_ENERGY_VOL_MIN("track_0_macro_energy_vol_min"),
    TRACK_0_MACRO_ENERGY_VOL_MAX("track_0_macro_energy_vol_max"),
    TRACK_0_MACRO_ENERGY_DENSITY_MIN("track_0_macro_energy_density_min"),
    TRACK_0_MACRO_ENERGY_DENSITY_MAX("track_0_macro_energy_density_max"),
    TRACK_0_MACRO_COMPLEXITY_SWING_MIN("track_0_macro_complexity_swing_min"),
    TRACK_0_MACRO_COMPLEXITY_SWING_MAX("track_0_macro_complexity_swing_max"),
    TRACK_0_MACRO_COMPLEXITY_VAR_MIN("track_0_macro_complexity_var_min"),
    TRACK_0_MACRO_COMPLEXITY_VAR_MAX("track_0_macro_complexity_var_max"),
    TRACK_0_MACRO_SPACE_DECAY_MIN("track_0_macro_space_decay_min"),
    TRACK_0_MACRO_SPACE_DECAY_MAX("track_0_macro_space_decay_max"),
    TRACK_0_MACRO_SPACE_REVERB_MIN("track_0_macro_space_reverb_min"),
    TRACK_0_MACRO_SPACE_REVERB_MAX("track_0_macro_space_reverb_max"),
    TRACK_0_MACRO_MOOD_HARM_MIN("track_0_macro_mood_harm_min"),
    TRACK_0_MACRO_MOOD_HARM_MAX("track_0_macro_mood_harm_max"),
    TRACK_0_MACRO_MOOD_TIMBRE_MIN("track_0_macro_mood_timbre_min"),
    TRACK_0_MACRO_MOOD_TIMBRE_MAX("track_0_macro_mood_timbre_max"),

    TRACK_1_MACRO_ENERGY_VOL_MIN("track_1_macro_energy_vol_min"),
    TRACK_1_MACRO_ENERGY_VOL_MAX("track_1_macro_energy_vol_max"),
    TRACK_1_MACRO_ENERGY_DENSITY_MIN("track_1_macro_energy_density_min"),
    TRACK_1_MACRO_ENERGY_DENSITY_MAX("track_1_macro_energy_density_max"),
    TRACK_1_MACRO_COMPLEXITY_SWING_MIN("track_1_macro_complexity_swing_min"),
    TRACK_1_MACRO_COMPLEXITY_SWING_MAX("track_1_macro_complexity_swing_max"),
    TRACK_1_MACRO_COMPLEXITY_VAR_MIN("track_1_macro_complexity_var_min"),
    TRACK_1_MACRO_COMPLEXITY_VAR_MAX("track_1_macro_complexity_var_max"),
    TRACK_1_MACRO_SPACE_DECAY_MIN("track_1_macro_space_decay_min"),
    TRACK_1_MACRO_SPACE_DECAY_MAX("track_1_macro_space_decay_max"),
    TRACK_1_MACRO_SPACE_REVERB_MIN("track_1_macro_space_reverb_min"),
    TRACK_1_MACRO_SPACE_REVERB_MAX("track_1_macro_space_reverb_max"),
    TRACK_1_MACRO_MOOD_HARM_MIN("track_1_macro_mood_harm_min"),
    TRACK_1_MACRO_MOOD_HARM_MAX("track_1_macro_mood_harm_max"),
    TRACK_1_MACRO_MOOD_TIMBRE_MIN("track_1_macro_mood_timbre_min"),
    TRACK_1_MACRO_MOOD_TIMBRE_MAX("track_1_macro_mood_timbre_max"),

    TRACK_2_MACRO_ENERGY_VOL_MIN("track_2_macro_energy_vol_min"),
    TRACK_2_MACRO_ENERGY_VOL_MAX("track_2_macro_energy_vol_max"),
    TRACK_2_MACRO_ENERGY_DENSITY_MIN("track_2_macro_energy_density_min"),
    TRACK_2_MACRO_ENERGY_DENSITY_MAX("track_2_macro_energy_density_max"),
    TRACK_2_MACRO_COMPLEXITY_SWING_MIN("track_2_macro_complexity_swing_min"),
    TRACK_2_MACRO_COMPLEXITY_SWING_MAX("track_2_macro_complexity_swing_max"),
    TRACK_2_MACRO_COMPLEXITY_VAR_MIN("track_2_macro_complexity_var_min"),
    TRACK_2_MACRO_COMPLEXITY_VAR_MAX("track_2_macro_complexity_var_max"),
    TRACK_2_MACRO_SPACE_DECAY_MIN("track_2_macro_space_decay_min"),
    TRACK_2_MACRO_SPACE_DECAY_MAX("track_2_macro_space_decay_max"),
    TRACK_2_MACRO_SPACE_REVERB_MIN("track_2_macro_space_reverb_min"),
    TRACK_2_MACRO_SPACE_REVERB_MAX("track_2_macro_space_reverb_max"),
    TRACK_2_MACRO_MOOD_HARM_MIN("track_2_macro_mood_harm_min"),
    TRACK_2_MACRO_MOOD_HARM_MAX("track_2_macro_mood_harm_max"),
    TRACK_2_MACRO_MOOD_TIMBRE_MIN("track_2_macro_mood_timbre_min"),
    TRACK_2_MACRO_MOOD_TIMBRE_MAX("track_2_macro_mood_timbre_max"),

    TRACK_3_MACRO_ENERGY_VOL_MIN("track_3_macro_energy_vol_min"),
    TRACK_3_MACRO_ENERGY_VOL_MAX("track_3_macro_energy_vol_max"),
    TRACK_3_MACRO_ENERGY_DENSITY_MIN("track_3_macro_energy_density_min"),
    TRACK_3_MACRO_ENERGY_DENSITY_MAX("track_3_macro_energy_density_max"),
    TRACK_3_MACRO_COMPLEXITY_SWING_MIN("track_3_macro_complexity_swing_min"),
    TRACK_3_MACRO_COMPLEXITY_SWING_MAX("track_3_macro_complexity_swing_max"),
    TRACK_3_MACRO_COMPLEXITY_VAR_MIN("track_3_macro_complexity_var_min"),
    TRACK_3_MACRO_COMPLEXITY_VAR_MAX("track_3_macro_complexity_var_max"),
    TRACK_3_MACRO_SPACE_DECAY_MIN("track_3_macro_space_decay_min"),
    TRACK_3_MACRO_SPACE_DECAY_MAX("track_3_macro_space_decay_max"),
    TRACK_3_MACRO_SPACE_REVERB_MIN("track_3_macro_space_reverb_min"),
    TRACK_3_MACRO_SPACE_REVERB_MAX("track_3_macro_space_reverb_max"),
    TRACK_3_MACRO_MOOD_HARM_MIN("track_3_macro_mood_harm_min"),
    TRACK_3_MACRO_MOOD_HARM_MAX("track_3_macro_mood_harm_max"),
    TRACK_3_MACRO_MOOD_TIMBRE_MIN("track_3_macro_mood_timbre_min"),
    TRACK_3_MACRO_MOOD_TIMBRE_MAX("track_3_macro_mood_timbre_max"),

    TRACK_4_MACRO_ENERGY_VOL_MIN("track_4_macro_energy_vol_min"),
    TRACK_4_MACRO_ENERGY_VOL_MAX("track_4_macro_energy_vol_max"),
    TRACK_4_MACRO_ENERGY_DENSITY_MIN("track_4_macro_energy_density_min"),
    TRACK_4_MACRO_ENERGY_DENSITY_MAX("track_4_macro_energy_density_max"),
    TRACK_4_MACRO_COMPLEXITY_SWING_MIN("track_4_macro_complexity_swing_min"),
    TRACK_4_MACRO_COMPLEXITY_SWING_MAX("track_4_macro_complexity_swing_max"),
    TRACK_4_MACRO_COMPLEXITY_VAR_MIN("track_4_macro_complexity_var_min"),
    TRACK_4_MACRO_COMPLEXITY_VAR_MAX("track_4_macro_complexity_var_max"),
    TRACK_4_MACRO_SPACE_DECAY_MIN("track_4_macro_space_decay_min"),
    TRACK_4_MACRO_SPACE_DECAY_MAX("track_4_macro_space_decay_max"),
    TRACK_4_MACRO_SPACE_REVERB_MIN("track_4_macro_space_reverb_min"),
    TRACK_4_MACRO_SPACE_REVERB_MAX("track_4_macro_space_reverb_max"),
    TRACK_4_MACRO_MOOD_HARM_MIN("track_4_macro_mood_harm_min"),
    TRACK_4_MACRO_MOOD_HARM_MAX("track_4_macro_mood_harm_max"),
    TRACK_4_MACRO_MOOD_TIMBRE_MIN("track_4_macro_mood_timbre_min"),
    TRACK_4_MACRO_MOOD_TIMBRE_MAX("track_4_macro_mood_timbre_max"),

    TRACK_5_MACRO_ENERGY_VOL_MIN("track_5_macro_energy_vol_min"),
    TRACK_5_MACRO_ENERGY_VOL_MAX("track_5_macro_energy_vol_max"),
    TRACK_5_MACRO_ENERGY_DENSITY_MIN("track_5_macro_energy_density_min"),
    TRACK_5_MACRO_ENERGY_DENSITY_MAX("track_5_macro_energy_density_max"),
    TRACK_5_MACRO_COMPLEXITY_SWING_MIN("track_5_macro_complexity_swing_min"),
    TRACK_5_MACRO_COMPLEXITY_SWING_MAX("track_5_macro_complexity_swing_max"),
    TRACK_5_MACRO_COMPLEXITY_VAR_MIN("track_5_macro_complexity_var_min"),
    TRACK_5_MACRO_COMPLEXITY_VAR_MAX("track_5_macro_complexity_var_max"),
    TRACK_5_MACRO_SPACE_DECAY_MIN("track_5_macro_space_decay_min"),
    TRACK_5_MACRO_SPACE_DECAY_MAX("track_5_macro_space_decay_max"),
    TRACK_5_MACRO_SPACE_REVERB_MIN("track_5_macro_space_reverb_min"),
    TRACK_5_MACRO_SPACE_REVERB_MAX("track_5_macro_space_reverb_max"),
    TRACK_5_MACRO_MOOD_HARM_MIN("track_5_macro_mood_harm_min"),
    TRACK_5_MACRO_MOOD_HARM_MAX("track_5_macro_mood_harm_max"),
    TRACK_5_MACRO_MOOD_TIMBRE_MIN("track_5_macro_mood_timbre_min"),
    TRACK_5_MACRO_MOOD_TIMBRE_MAX("track_5_macro_mood_timbre_max"),

    TRACK_6_MACRO_ENERGY_VOL_MIN("track_6_macro_energy_vol_min"),
    TRACK_6_MACRO_ENERGY_VOL_MAX("track_6_macro_energy_vol_max"),
    TRACK_6_MACRO_ENERGY_DENSITY_MIN("track_6_macro_energy_density_min"),
    TRACK_6_MACRO_ENERGY_DENSITY_MAX("track_6_macro_energy_density_max"),
    TRACK_6_MACRO_COMPLEXITY_SWING_MIN("track_6_macro_complexity_swing_min"),
    TRACK_6_MACRO_COMPLEXITY_SWING_MAX("track_6_macro_complexity_swing_max"),
    TRACK_6_MACRO_COMPLEXITY_VAR_MIN("track_6_macro_complexity_var_min"),
    TRACK_6_MACRO_COMPLEXITY_VAR_MAX("track_6_macro_complexity_var_max"),
    TRACK_6_MACRO_SPACE_DECAY_MIN("track_6_macro_space_decay_min"),
    TRACK_6_MACRO_SPACE_DECAY_MAX("track_6_macro_space_decay_max"),
    TRACK_6_MACRO_SPACE_REVERB_MIN("track_6_macro_space_reverb_min"),
    TRACK_6_MACRO_SPACE_REVERB_MAX("track_6_macro_space_reverb_max"),
    TRACK_6_MACRO_MOOD_HARM_MIN("track_6_macro_mood_harm_min"),
    TRACK_6_MACRO_MOOD_HARM_MAX("track_6_macro_mood_harm_max"),
    TRACK_6_MACRO_MOOD_TIMBRE_MIN("track_6_macro_mood_timbre_min"),
    TRACK_6_MACRO_MOOD_TIMBRE_MAX("track_6_macro_mood_timbre_max"),

    TRACK_7_MACRO_ENERGY_VOL_MIN("track_7_macro_energy_vol_min"),
    TRACK_7_MACRO_ENERGY_VOL_MAX("track_7_macro_energy_vol_max"),
    TRACK_7_MACRO_ENERGY_DENSITY_MIN("track_7_macro_energy_density_min"),
    TRACK_7_MACRO_ENERGY_DENSITY_MAX("track_7_macro_energy_density_max"),
    TRACK_7_MACRO_COMPLEXITY_SWING_MIN("track_7_macro_complexity_swing_min"),
    TRACK_7_MACRO_COMPLEXITY_SWING_MAX("track_7_macro_complexity_swing_max"),
    TRACK_7_MACRO_COMPLEXITY_VAR_MIN("track_7_macro_complexity_var_min"),
    TRACK_7_MACRO_COMPLEXITY_VAR_MAX("track_7_macro_complexity_var_max"),
    TRACK_7_MACRO_SPACE_DECAY_MIN("track_7_macro_space_decay_min"),
    TRACK_7_MACRO_SPACE_DECAY_MAX("track_7_macro_space_decay_max"),
    TRACK_7_MACRO_SPACE_REVERB_MIN("track_7_macro_space_reverb_min"),
    TRACK_7_MACRO_SPACE_REVERB_MAX("track_7_macro_space_reverb_max"),
    TRACK_7_MACRO_MOOD_HARM_MIN("track_7_macro_mood_harm_min"),
    TRACK_7_MACRO_MOOD_HARM_MAX("track_7_macro_mood_harm_max"),
    TRACK_7_MACRO_MOOD_TIMBRE_MIN("track_7_macro_mood_timbre_min"),
    TRACK_7_MACRO_MOOD_TIMBRE_MAX("track_7_macro_mood_timbre_max"),

    // Genre profile (13 entries)
    GENRE_DENSITY_0("genre_density_0"),
    GENRE_DENSITY_1("genre_density_1"),
    GENRE_DENSITY_2("genre_density_2"),
    GENRE_DENSITY_3("genre_density_3"),
    GENRE_DENSITY_4("genre_density_4"),
    GENRE_DENSITY_5("genre_density_5"),
    GENRE_DENSITY_6("genre_density_6"),
    GENRE_DENSITY_7("genre_density_7"),
    GENRE_SWING("genre_swing"),
    GENRE_GHOST_PROB("genre_ghost_prob"),
    GENRE_NOTE_RANGE_LOW("genre_note_range_low"),
    GENRE_NOTE_RANGE_HIGH("genre_note_range_high"),
    GENRE_RHYTHM_PATTERN("genre_rhythm_pattern"),

    // Lick buffer (97 entries)
    LICK_LENGTH("lick_length"),
    LICK_DATA_0("lick_data_0"),
    LICK_DATA_1("lick_data_1"),
    LICK_DATA_2("lick_data_2"),
    LICK_DATA_3("lick_data_3"),
    LICK_DATA_4("lick_data_4"),
    LICK_DATA_5("lick_data_5"),
    LICK_DATA_6("lick_data_6"),
    LICK_DATA_7("lick_data_7"),
    LICK_DATA_8("lick_data_8"),
    LICK_DATA_9("lick_data_9"),
    LICK_DATA_10("lick_data_10"),
    LICK_DATA_11("lick_data_11"),
    LICK_DATA_12("lick_data_12"),
    LICK_DATA_13("lick_data_13"),
    LICK_DATA_14("lick_data_14"),
    LICK_DATA_15("lick_data_15"),
    LICK_DATA_16("lick_data_16"),
    LICK_DATA_17("lick_data_17"),
    LICK_DATA_18("lick_data_18"),
    LICK_DATA_19("lick_data_19"),
    LICK_DATA_20("lick_data_20"),
    LICK_DATA_21("lick_data_21"),
    LICK_DATA_22("lick_data_22"),
    LICK_DATA_23("lick_data_23"),
    LICK_DATA_24("lick_data_24"),
    LICK_DATA_25("lick_data_25"),
    LICK_DATA_26("lick_data_26"),
    LICK_DATA_27("lick_data_27"),
    LICK_DATA_28("lick_data_28"),
    LICK_DATA_29("lick_data_29"),
    LICK_DATA_30("lick_data_30"),
    LICK_DATA_31("lick_data_31"),
    LICK_DATA_32("lick_data_32"),
    LICK_DATA_33("lick_data_33"),
    LICK_DATA_34("lick_data_34"),
    LICK_DATA_35("lick_data_35"),
    LICK_DATA_36("lick_data_36"),
    LICK_DATA_37("lick_data_37"),
    LICK_DATA_38("lick_data_38"),
    LICK_DATA_39("lick_data_39"),
    LICK_DATA_40("lick_data_40"),
    LICK_DATA_41("lick_data_41"),
    LICK_DATA_42("lick_data_42"),
    LICK_DATA_43("lick_data_43"),
    LICK_DATA_44("lick_data_44"),
    LICK_DATA_45("lick_data_45"),
    LICK_DATA_46("lick_data_46"),
    LICK_DATA_47("lick_data_47"),
    LICK_DATA_48("lick_data_48"),
    LICK_DATA_49("lick_data_49"),
    LICK_DATA_50("lick_data_50"),
    LICK_DATA_51("lick_data_51"),
    LICK_DATA_52("lick_data_52"),
    LICK_DATA_53("lick_data_53"),
    LICK_DATA_54("lick_data_54"),
    LICK_DATA_55("lick_data_55"),
    LICK_DATA_56("lick_data_56"),
    LICK_DATA_57("lick_data_57"),
    LICK_DATA_58("lick_data_58"),
    LICK_DATA_59("lick_data_59"),
    LICK_DATA_60("lick_data_60"),
    LICK_DATA_61("lick_data_61"),
    LICK_DATA_62("lick_data_62"),
    LICK_DATA_63("lick_data_63"),
    LICK_DATA_64("lick_data_64"),
    LICK_DATA_65("lick_data_65"),
    LICK_DATA_66("lick_data_66"),
    LICK_DATA_67("lick_data_67"),
    LICK_DATA_68("lick_data_68"),
    LICK_DATA_69("lick_data_69"),
    LICK_DATA_70("lick_data_70"),
    LICK_DATA_71("lick_data_71"),
    LICK_DATA_72("lick_data_72"),
    LICK_DATA_73("lick_data_73"),
    LICK_DATA_74("lick_data_74"),
    LICK_DATA_75("lick_data_75"),
    LICK_DATA_76("lick_data_76"),
    LICK_DATA_77("lick_data_77"),
    LICK_DATA_78("lick_data_78"),
    LICK_DATA_79("lick_data_79"),
    LICK_DATA_80("lick_data_80"),
    LICK_DATA_81("lick_data_81"),
    LICK_DATA_82("lick_data_82"),
    LICK_DATA_83("lick_data_83"),
    LICK_DATA_84("lick_data_84"),
    LICK_DATA_85("lick_data_85"),
    LICK_DATA_86("lick_data_86"),
    LICK_DATA_87("lick_data_87"),
    LICK_DATA_88("lick_data_88"),
    LICK_DATA_89("lick_data_89"),
    LICK_DATA_90("lick_data_90"),
    LICK_DATA_91("lick_data_91"),
    LICK_DATA_92("lick_data_92"),
    LICK_DATA_93("lick_data_93"),
    LICK_DATA_94("lick_data_94"),
    LICK_DATA_95("lick_data_95"),
}
