package org.balch.orpheus.core.plugin.symbols

import org.balch.orpheus.core.plugin.PortSymbol
import org.balch.orpheus.core.plugin.Symbol

const val PULSAR_URI = "org.balch.orpheus.plugins.pulsar"

enum class PulsarSymbol(
    override val symbol: Symbol,
    override val uri: String = PULSAR_URI,
    override val displayName: String = symbol.replaceFirstChar { it.uppercase() }
) : PortSymbol {
    PLAYING("playing", displayName = "Playing"),
    VIBE_GENERATION("vibe_generation"),
    ENERGY("energy", displayName = "Energy"),
    COMPLEXITY("complexity", displayName = "Complexity"),
    SPACE("space", displayName = "Space"),
    MOOD("mood", displayName = "Mood"),
    BPM("bpm", displayName = "BPM"),
    DEEP("deep", displayName = "Deep"),
    ROOT_NOTE("root_note", displayName = "Root Note"),
    SCALE("scale", displayName = "Scale"),
    MIX("mix", displayName = "Mix"),
    PERC_MIX("perc_mix", displayName = "Percussion Mix"),
    ENVELOPE_MODE("envelope_mode", displayName = "Envelope Mode"),
    SEED("seed"),
    LICK_MUTATION("lick_mutation"),
    LICK_OCTAVE("lick_octave"),

    // Per-track engine selectors (16 entries)
    TRACK_0_ENGINE_EDM("track_0_engine_edm", displayName = "Track 0 EDM Engine"),
    TRACK_0_ENGINE_SPACE("track_0_engine_space", displayName = "Track 0 Space Engine"),
    TRACK_1_ENGINE_EDM("track_1_engine_edm", displayName = "Track 1 EDM Engine"),
    TRACK_1_ENGINE_SPACE("track_1_engine_space", displayName = "Track 1 Space Engine"),
    TRACK_2_ENGINE_EDM("track_2_engine_edm", displayName = "Track 2 EDM Engine"),
    TRACK_2_ENGINE_SPACE("track_2_engine_space", displayName = "Track 2 Space Engine"),
    TRACK_3_ENGINE_EDM("track_3_engine_edm", displayName = "Track 3 EDM Engine"),
    TRACK_3_ENGINE_SPACE("track_3_engine_space", displayName = "Track 3 Space Engine"),
    TRACK_4_ENGINE_EDM("track_4_engine_edm", displayName = "Track 4 EDM Engine"),
    TRACK_4_ENGINE_SPACE("track_4_engine_space", displayName = "Track 4 Space Engine"),
    TRACK_5_ENGINE_EDM("track_5_engine_edm", displayName = "Track 5 EDM Engine"),
    TRACK_5_ENGINE_SPACE("track_5_engine_space", displayName = "Track 5 Space Engine"),
    TRACK_6_ENGINE_EDM("track_6_engine_edm", displayName = "Track 6 EDM Engine"),
    TRACK_6_ENGINE_SPACE("track_6_engine_space", displayName = "Track 6 Space Engine"),
    TRACK_7_ENGINE_EDM("track_7_engine_edm", displayName = "Track 7 EDM Engine"),
    TRACK_7_ENGINE_SPACE("track_7_engine_space", displayName = "Track 7 Space Engine"),

    // Per-track voice params: VOLUME (8 entries)
    TRACK_0_VOLUME("track_0_volume"),
    TRACK_1_VOLUME("track_1_volume"),
    TRACK_2_VOLUME("track_2_volume"),
    TRACK_3_VOLUME("track_3_volume"),
    TRACK_4_VOLUME("track_4_volume"),
    TRACK_5_VOLUME("track_5_volume"),
    TRACK_6_VOLUME("track_6_volume"),
    TRACK_7_VOLUME("track_7_volume"),

    // Per-track voice params: PAN (8 entries)
    TRACK_0_PAN("track_0_pan"),
    TRACK_1_PAN("track_1_pan"),
    TRACK_2_PAN("track_2_pan"),
    TRACK_3_PAN("track_3_pan"),
    TRACK_4_PAN("track_4_pan"),
    TRACK_5_PAN("track_5_pan"),
    TRACK_6_PAN("track_6_pan"),
    TRACK_7_PAN("track_7_pan"),

    // Per-track voice params: HARMONICS (8 entries)
    TRACK_0_HARMONICS("track_0_harmonics"),
    TRACK_1_HARMONICS("track_1_harmonics"),
    TRACK_2_HARMONICS("track_2_harmonics"),
    TRACK_3_HARMONICS("track_3_harmonics"),
    TRACK_4_HARMONICS("track_4_harmonics"),
    TRACK_5_HARMONICS("track_5_harmonics"),
    TRACK_6_HARMONICS("track_6_harmonics"),
    TRACK_7_HARMONICS("track_7_harmonics"),

    // Per-track voice params: TIMBRE (8 entries)
    TRACK_0_TIMBRE("track_0_timbre"),
    TRACK_1_TIMBRE("track_1_timbre"),
    TRACK_2_TIMBRE("track_2_timbre"),
    TRACK_3_TIMBRE("track_3_timbre"),
    TRACK_4_TIMBRE("track_4_timbre"),
    TRACK_5_TIMBRE("track_5_timbre"),
    TRACK_6_TIMBRE("track_6_timbre"),
    TRACK_7_TIMBRE("track_7_timbre"),

    // Per-track voice params: MORPH (8 entries)
    TRACK_0_MORPH("track_0_morph"),
    TRACK_1_MORPH("track_1_morph"),
    TRACK_2_MORPH("track_2_morph"),
    TRACK_3_MORPH("track_3_morph"),
    TRACK_4_MORPH("track_4_morph"),
    TRACK_5_MORPH("track_5_morph"),
    TRACK_6_MORPH("track_6_morph"),
    TRACK_7_MORPH("track_7_morph"),

    // Per-track voice params: ENVELOPE (8 entries)
    TRACK_0_ENVELOPE("track_0_envelope"),
    TRACK_1_ENVELOPE("track_1_envelope"),
    TRACK_2_ENVELOPE("track_2_envelope"),
    TRACK_3_ENVELOPE("track_3_envelope"),
    TRACK_4_ENVELOPE("track_4_envelope"),
    TRACK_5_ENVELOPE("track_5_envelope"),
    TRACK_6_ENVELOPE("track_6_envelope"),
    TRACK_7_ENVELOPE("track_7_envelope"),

    // Per-track role: 0=PERCUSSIVE, 1=MELODIC, 2=CHORDAL
    TRACK_0_ROLE("track_0_role"),
    TRACK_1_ROLE("track_1_role"),
    TRACK_2_ROLE("track_2_role"),
    TRACK_3_ROLE("track_3_role"),
    TRACK_4_ROLE("track_4_role"),
    TRACK_5_ROLE("track_5_role"),
    TRACK_6_ROLE("track_6_role"),
    TRACK_7_ROLE("track_7_role"),

    // Per-track bar strategy (8 entries)
    TRACK_0_BAR_STRATEGY("track_0_bar_strategy"),
    TRACK_1_BAR_STRATEGY("track_1_bar_strategy"),
    TRACK_2_BAR_STRATEGY("track_2_bar_strategy"),
    TRACK_3_BAR_STRATEGY("track_3_bar_strategy"),
    TRACK_4_BAR_STRATEGY("track_4_bar_strategy"),
    TRACK_5_BAR_STRATEGY("track_5_bar_strategy"),
    TRACK_6_BAR_STRATEGY("track_6_bar_strategy"),
    TRACK_7_BAR_STRATEGY("track_7_bar_strategy"),

    // Per-track evolution: rhythmic MUTATE enable (0/1)
    TRACK_0_EVO_RHYTHMIC("track_0_evo_rhythmic"),
    TRACK_1_EVO_RHYTHMIC("track_1_evo_rhythmic"),
    TRACK_2_EVO_RHYTHMIC("track_2_evo_rhythmic"),
    TRACK_3_EVO_RHYTHMIC("track_3_evo_rhythmic"),
    TRACK_4_EVO_RHYTHMIC("track_4_evo_rhythmic"),
    TRACK_5_EVO_RHYTHMIC("track_5_evo_rhythmic"),
    TRACK_6_EVO_RHYTHMIC("track_6_evo_rhythmic"),
    TRACK_7_EVO_RHYTHMIC("track_7_evo_rhythmic"),

    // Vibe step count
    STEP_COUNT("step_count"),

    // Per-track macro maps: ENERGY_VOL (16 entries per track × 8 tracks = 128)
    TRACK_0_MACRO_ENERGY_VOL_MIN("track_0_macro_energy_vol_min"),
    TRACK_0_MACRO_ENERGY_VOL_MAX("track_0_macro_energy_vol_max"),
    TRACK_0_MACRO_ENERGY_DENSITY_MIN("track_0_macro_energy_density_min"),
    TRACK_0_MACRO_ENERGY_DENSITY_MAX("track_0_macro_energy_density_max"),
    TRACK_0_MACRO_COMPLEXITY_SWING_MIN("track_0_macro_complexity_swing_min"),
    TRACK_0_MACRO_COMPLEXITY_SWING_MAX("track_0_macro_complexity_swing_max"),
    TRACK_0_MACRO_COMPLEXITY_VAR_MIN("track_0_macro_complexity_var_min"),
    TRACK_0_MACRO_COMPLEXITY_VAR_MAX("track_0_macro_complexity_var_max"),
    TRACK_0_MACRO_SPACE_DECAY_MIN("track_0_macro_space_decay_min"),
    TRACK_0_MACRO_SPACE_DECAY_MAX("track_0_macro_space_decay_max"),
    TRACK_0_MACRO_MOOD_HARM_MIN("track_0_macro_mood_harm_min"),
    TRACK_0_MACRO_MOOD_HARM_MAX("track_0_macro_mood_harm_max"),
    TRACK_0_MACRO_MOOD_TIMBRE_MIN("track_0_macro_mood_timbre_min"),
    TRACK_0_MACRO_MOOD_TIMBRE_MAX("track_0_macro_mood_timbre_max"),

    TRACK_1_MACRO_ENERGY_VOL_MIN("track_1_macro_energy_vol_min"),
    TRACK_1_MACRO_ENERGY_VOL_MAX("track_1_macro_energy_vol_max"),
    TRACK_1_MACRO_ENERGY_DENSITY_MIN("track_1_macro_energy_density_min"),
    TRACK_1_MACRO_ENERGY_DENSITY_MAX("track_1_macro_energy_density_max"),
    TRACK_1_MACRO_COMPLEXITY_SWING_MIN("track_1_macro_complexity_swing_min"),
    TRACK_1_MACRO_COMPLEXITY_SWING_MAX("track_1_macro_complexity_swing_max"),
    TRACK_1_MACRO_COMPLEXITY_VAR_MIN("track_1_macro_complexity_var_min"),
    TRACK_1_MACRO_COMPLEXITY_VAR_MAX("track_1_macro_complexity_var_max"),
    TRACK_1_MACRO_SPACE_DECAY_MIN("track_1_macro_space_decay_min"),
    TRACK_1_MACRO_SPACE_DECAY_MAX("track_1_macro_space_decay_max"),
    TRACK_1_MACRO_MOOD_HARM_MIN("track_1_macro_mood_harm_min"),
    TRACK_1_MACRO_MOOD_HARM_MAX("track_1_macro_mood_harm_max"),
    TRACK_1_MACRO_MOOD_TIMBRE_MIN("track_1_macro_mood_timbre_min"),
    TRACK_1_MACRO_MOOD_TIMBRE_MAX("track_1_macro_mood_timbre_max"),

    TRACK_2_MACRO_ENERGY_VOL_MIN("track_2_macro_energy_vol_min"),
    TRACK_2_MACRO_ENERGY_VOL_MAX("track_2_macro_energy_vol_max"),
    TRACK_2_MACRO_ENERGY_DENSITY_MIN("track_2_macro_energy_density_min"),
    TRACK_2_MACRO_ENERGY_DENSITY_MAX("track_2_macro_energy_density_max"),
    TRACK_2_MACRO_COMPLEXITY_SWING_MIN("track_2_macro_complexity_swing_min"),
    TRACK_2_MACRO_COMPLEXITY_SWING_MAX("track_2_macro_complexity_swing_max"),
    TRACK_2_MACRO_COMPLEXITY_VAR_MIN("track_2_macro_complexity_var_min"),
    TRACK_2_MACRO_COMPLEXITY_VAR_MAX("track_2_macro_complexity_var_max"),
    TRACK_2_MACRO_SPACE_DECAY_MIN("track_2_macro_space_decay_min"),
    TRACK_2_MACRO_SPACE_DECAY_MAX("track_2_macro_space_decay_max"),
    TRACK_2_MACRO_MOOD_HARM_MIN("track_2_macro_mood_harm_min"),
    TRACK_2_MACRO_MOOD_HARM_MAX("track_2_macro_mood_harm_max"),
    TRACK_2_MACRO_MOOD_TIMBRE_MIN("track_2_macro_mood_timbre_min"),
    TRACK_2_MACRO_MOOD_TIMBRE_MAX("track_2_macro_mood_timbre_max"),

    TRACK_3_MACRO_ENERGY_VOL_MIN("track_3_macro_energy_vol_min"),
    TRACK_3_MACRO_ENERGY_VOL_MAX("track_3_macro_energy_vol_max"),
    TRACK_3_MACRO_ENERGY_DENSITY_MIN("track_3_macro_energy_density_min"),
    TRACK_3_MACRO_ENERGY_DENSITY_MAX("track_3_macro_energy_density_max"),
    TRACK_3_MACRO_COMPLEXITY_SWING_MIN("track_3_macro_complexity_swing_min"),
    TRACK_3_MACRO_COMPLEXITY_SWING_MAX("track_3_macro_complexity_swing_max"),
    TRACK_3_MACRO_COMPLEXITY_VAR_MIN("track_3_macro_complexity_var_min"),
    TRACK_3_MACRO_COMPLEXITY_VAR_MAX("track_3_macro_complexity_var_max"),
    TRACK_3_MACRO_SPACE_DECAY_MIN("track_3_macro_space_decay_min"),
    TRACK_3_MACRO_SPACE_DECAY_MAX("track_3_macro_space_decay_max"),
    TRACK_3_MACRO_MOOD_HARM_MIN("track_3_macro_mood_harm_min"),
    TRACK_3_MACRO_MOOD_HARM_MAX("track_3_macro_mood_harm_max"),
    TRACK_3_MACRO_MOOD_TIMBRE_MIN("track_3_macro_mood_timbre_min"),
    TRACK_3_MACRO_MOOD_TIMBRE_MAX("track_3_macro_mood_timbre_max"),

    TRACK_4_MACRO_ENERGY_VOL_MIN("track_4_macro_energy_vol_min"),
    TRACK_4_MACRO_ENERGY_VOL_MAX("track_4_macro_energy_vol_max"),
    TRACK_4_MACRO_ENERGY_DENSITY_MIN("track_4_macro_energy_density_min"),
    TRACK_4_MACRO_ENERGY_DENSITY_MAX("track_4_macro_energy_density_max"),
    TRACK_4_MACRO_COMPLEXITY_SWING_MIN("track_4_macro_complexity_swing_min"),
    TRACK_4_MACRO_COMPLEXITY_SWING_MAX("track_4_macro_complexity_swing_max"),
    TRACK_4_MACRO_COMPLEXITY_VAR_MIN("track_4_macro_complexity_var_min"),
    TRACK_4_MACRO_COMPLEXITY_VAR_MAX("track_4_macro_complexity_var_max"),
    TRACK_4_MACRO_SPACE_DECAY_MIN("track_4_macro_space_decay_min"),
    TRACK_4_MACRO_SPACE_DECAY_MAX("track_4_macro_space_decay_max"),
    TRACK_4_MACRO_MOOD_HARM_MIN("track_4_macro_mood_harm_min"),
    TRACK_4_MACRO_MOOD_HARM_MAX("track_4_macro_mood_harm_max"),
    TRACK_4_MACRO_MOOD_TIMBRE_MIN("track_4_macro_mood_timbre_min"),
    TRACK_4_MACRO_MOOD_TIMBRE_MAX("track_4_macro_mood_timbre_max"),

    TRACK_5_MACRO_ENERGY_VOL_MIN("track_5_macro_energy_vol_min"),
    TRACK_5_MACRO_ENERGY_VOL_MAX("track_5_macro_energy_vol_max"),
    TRACK_5_MACRO_ENERGY_DENSITY_MIN("track_5_macro_energy_density_min"),
    TRACK_5_MACRO_ENERGY_DENSITY_MAX("track_5_macro_energy_density_max"),
    TRACK_5_MACRO_COMPLEXITY_SWING_MIN("track_5_macro_complexity_swing_min"),
    TRACK_5_MACRO_COMPLEXITY_SWING_MAX("track_5_macro_complexity_swing_max"),
    TRACK_5_MACRO_COMPLEXITY_VAR_MIN("track_5_macro_complexity_var_min"),
    TRACK_5_MACRO_COMPLEXITY_VAR_MAX("track_5_macro_complexity_var_max"),
    TRACK_5_MACRO_SPACE_DECAY_MIN("track_5_macro_space_decay_min"),
    TRACK_5_MACRO_SPACE_DECAY_MAX("track_5_macro_space_decay_max"),
    TRACK_5_MACRO_MOOD_HARM_MIN("track_5_macro_mood_harm_min"),
    TRACK_5_MACRO_MOOD_HARM_MAX("track_5_macro_mood_harm_max"),
    TRACK_5_MACRO_MOOD_TIMBRE_MIN("track_5_macro_mood_timbre_min"),
    TRACK_5_MACRO_MOOD_TIMBRE_MAX("track_5_macro_mood_timbre_max"),

    TRACK_6_MACRO_ENERGY_VOL_MIN("track_6_macro_energy_vol_min"),
    TRACK_6_MACRO_ENERGY_VOL_MAX("track_6_macro_energy_vol_max"),
    TRACK_6_MACRO_ENERGY_DENSITY_MIN("track_6_macro_energy_density_min"),
    TRACK_6_MACRO_ENERGY_DENSITY_MAX("track_6_macro_energy_density_max"),
    TRACK_6_MACRO_COMPLEXITY_SWING_MIN("track_6_macro_complexity_swing_min"),
    TRACK_6_MACRO_COMPLEXITY_SWING_MAX("track_6_macro_complexity_swing_max"),
    TRACK_6_MACRO_COMPLEXITY_VAR_MIN("track_6_macro_complexity_var_min"),
    TRACK_6_MACRO_COMPLEXITY_VAR_MAX("track_6_macro_complexity_var_max"),
    TRACK_6_MACRO_SPACE_DECAY_MIN("track_6_macro_space_decay_min"),
    TRACK_6_MACRO_SPACE_DECAY_MAX("track_6_macro_space_decay_max"),
    TRACK_6_MACRO_MOOD_HARM_MIN("track_6_macro_mood_harm_min"),
    TRACK_6_MACRO_MOOD_HARM_MAX("track_6_macro_mood_harm_max"),
    TRACK_6_MACRO_MOOD_TIMBRE_MIN("track_6_macro_mood_timbre_min"),
    TRACK_6_MACRO_MOOD_TIMBRE_MAX("track_6_macro_mood_timbre_max"),

    TRACK_7_MACRO_ENERGY_VOL_MIN("track_7_macro_energy_vol_min"),
    TRACK_7_MACRO_ENERGY_VOL_MAX("track_7_macro_energy_vol_max"),
    TRACK_7_MACRO_ENERGY_DENSITY_MIN("track_7_macro_energy_density_min"),
    TRACK_7_MACRO_ENERGY_DENSITY_MAX("track_7_macro_energy_density_max"),
    TRACK_7_MACRO_COMPLEXITY_SWING_MIN("track_7_macro_complexity_swing_min"),
    TRACK_7_MACRO_COMPLEXITY_SWING_MAX("track_7_macro_complexity_swing_max"),
    TRACK_7_MACRO_COMPLEXITY_VAR_MIN("track_7_macro_complexity_var_min"),
    TRACK_7_MACRO_COMPLEXITY_VAR_MAX("track_7_macro_complexity_var_max"),
    TRACK_7_MACRO_SPACE_DECAY_MIN("track_7_macro_space_decay_min"),
    TRACK_7_MACRO_SPACE_DECAY_MAX("track_7_macro_space_decay_max"),
    TRACK_7_MACRO_MOOD_HARM_MIN("track_7_macro_mood_harm_min"),
    TRACK_7_MACRO_MOOD_HARM_MAX("track_7_macro_mood_harm_max"),
    TRACK_7_MACRO_MOOD_TIMBRE_MIN("track_7_macro_mood_timbre_min"),
    TRACK_7_MACRO_MOOD_TIMBRE_MAX("track_7_macro_mood_timbre_max"),

    // Genre profile (13 entries)
    GENRE_DENSITY_0("genre_density_0"),
    GENRE_DENSITY_1("genre_density_1"),
    GENRE_DENSITY_2("genre_density_2"),
    GENRE_DENSITY_3("genre_density_3"),
    GENRE_DENSITY_4("genre_density_4"),
    GENRE_DENSITY_5("genre_density_5"),
    GENRE_DENSITY_6("genre_density_6"),
    GENRE_DENSITY_7("genre_density_7"),
    GENRE_SWING("genre_swing"),
    GENRE_GHOST_PROB("genre_ghost_prob"),
    GENRE_NOTE_RANGE_LOW("genre_note_range_low"),
    GENRE_NOTE_RANGE_HIGH("genre_note_range_high"),
    GENRE_RHYTHM_DENSITY("genre_rhythm_density"),

    // Lick buffer (98 entries)
    LICK_LENGTH("lick_length"),
    LICK_LOOP_LENGTH("lick_loop_length"),
    LICK_DATA_0("lick_data_0"),
    LICK_DATA_1("lick_data_1"),
    LICK_DATA_2("lick_data_2"),
    LICK_DATA_3("lick_data_3"),
    LICK_DATA_4("lick_data_4"),
    LICK_DATA_5("lick_data_5"),
    LICK_DATA_6("lick_data_6"),
    LICK_DATA_7("lick_data_7"),
    LICK_DATA_8("lick_data_8"),
    LICK_DATA_9("lick_data_9"),
    LICK_DATA_10("lick_data_10"),
    LICK_DATA_11("lick_data_11"),
    LICK_DATA_12("lick_data_12"),
    LICK_DATA_13("lick_data_13"),
    LICK_DATA_14("lick_data_14"),
    LICK_DATA_15("lick_data_15"),
    LICK_DATA_16("lick_data_16"),
    LICK_DATA_17("lick_data_17"),
    LICK_DATA_18("lick_data_18"),
    LICK_DATA_19("lick_data_19"),
    LICK_DATA_20("lick_data_20"),
    LICK_DATA_21("lick_data_21"),
    LICK_DATA_22("lick_data_22"),
    LICK_DATA_23("lick_data_23"),
    LICK_DATA_24("lick_data_24"),
    LICK_DATA_25("lick_data_25"),
    LICK_DATA_26("lick_data_26"),
    LICK_DATA_27("lick_data_27"),
    LICK_DATA_28("lick_data_28"),
    LICK_DATA_29("lick_data_29"),
    LICK_DATA_30("lick_data_30"),
    LICK_DATA_31("lick_data_31"),
    LICK_DATA_32("lick_data_32"),
    LICK_DATA_33("lick_data_33"),
    LICK_DATA_34("lick_data_34"),
    LICK_DATA_35("lick_data_35"),
    LICK_DATA_36("lick_data_36"),
    LICK_DATA_37("lick_data_37"),
    LICK_DATA_38("lick_data_38"),
    LICK_DATA_39("lick_data_39"),
    LICK_DATA_40("lick_data_40"),
    LICK_DATA_41("lick_data_41"),
    LICK_DATA_42("lick_data_42"),
    LICK_DATA_43("lick_data_43"),
    LICK_DATA_44("lick_data_44"),
    LICK_DATA_45("lick_data_45"),
    LICK_DATA_46("lick_data_46"),
    LICK_DATA_47("lick_data_47"),
    LICK_DATA_48("lick_data_48"),
    LICK_DATA_49("lick_data_49"),
    LICK_DATA_50("lick_data_50"),
    LICK_DATA_51("lick_data_51"),
    LICK_DATA_52("lick_data_52"),
    LICK_DATA_53("lick_data_53"),
    LICK_DATA_54("lick_data_54"),
    LICK_DATA_55("lick_data_55"),
    LICK_DATA_56("lick_data_56"),
    LICK_DATA_57("lick_data_57"),
    LICK_DATA_58("lick_data_58"),
    LICK_DATA_59("lick_data_59"),
    LICK_DATA_60("lick_data_60"),
    LICK_DATA_61("lick_data_61"),
    LICK_DATA_62("lick_data_62"),
    LICK_DATA_63("lick_data_63"),
    LICK_DATA_64("lick_data_64"),
    LICK_DATA_65("lick_data_65"),
    LICK_DATA_66("lick_data_66"),
    LICK_DATA_67("lick_data_67"),
    LICK_DATA_68("lick_data_68"),
    LICK_DATA_69("lick_data_69"),
    LICK_DATA_70("lick_data_70"),
    LICK_DATA_71("lick_data_71"),
    LICK_DATA_72("lick_data_72"),
    LICK_DATA_73("lick_data_73"),
    LICK_DATA_74("lick_data_74"),
    LICK_DATA_75("lick_data_75"),
    LICK_DATA_76("lick_data_76"),
    LICK_DATA_77("lick_data_77"),
    LICK_DATA_78("lick_data_78"),
    LICK_DATA_79("lick_data_79"),
    LICK_DATA_80("lick_data_80"),
    LICK_DATA_81("lick_data_81"),
    LICK_DATA_82("lick_data_82"),
    LICK_DATA_83("lick_data_83"),
    LICK_DATA_84("lick_data_84"),
    LICK_DATA_85("lick_data_85"),
    LICK_DATA_86("lick_data_86"),
    LICK_DATA_87("lick_data_87"),
    LICK_DATA_88("lick_data_88"),
    LICK_DATA_89("lick_data_89"),
    LICK_DATA_90("lick_data_90"),
    LICK_DATA_91("lick_data_91"),
    LICK_DATA_92("lick_data_92"),
    LICK_DATA_93("lick_data_93"),
    LICK_DATA_94("lick_data_94"),
    LICK_DATA_95("lick_data_95"),
    // Per-step glide overrides (-1 = use track default). Stride is now 4 floats
    // per lick step: 0=scale_degree, 1=duration, 2=velocity, 3=glide_rate.
    LICK_DATA_96("lick_data_96"),
    LICK_DATA_97("lick_data_97"),
    LICK_DATA_98("lick_data_98"),
    LICK_DATA_99("lick_data_99"),
    LICK_DATA_100("lick_data_100"),
    LICK_DATA_101("lick_data_101"),
    LICK_DATA_102("lick_data_102"),
    LICK_DATA_103("lick_data_103"),
    LICK_DATA_104("lick_data_104"),
    LICK_DATA_105("lick_data_105"),
    LICK_DATA_106("lick_data_106"),
    LICK_DATA_107("lick_data_107"),
    LICK_DATA_108("lick_data_108"),
    LICK_DATA_109("lick_data_109"),
    LICK_DATA_110("lick_data_110"),
    LICK_DATA_111("lick_data_111"),
    LICK_DATA_112("lick_data_112"),
    LICK_DATA_113("lick_data_113"),
    LICK_DATA_114("lick_data_114"),
    LICK_DATA_115("lick_data_115"),
    LICK_DATA_116("lick_data_116"),
    LICK_DATA_117("lick_data_117"),
    LICK_DATA_118("lick_data_118"),
    LICK_DATA_119("lick_data_119"),
    LICK_DATA_120("lick_data_120"),
    LICK_DATA_121("lick_data_121"),
    LICK_DATA_122("lick_data_122"),
    LICK_DATA_123("lick_data_123"),
    LICK_DATA_124("lick_data_124"),
    LICK_DATA_125("lick_data_125"),
    LICK_DATA_126("lick_data_126"),
    LICK_DATA_127("lick_data_127"),

    // Chord progression
    GENRE_PROGRESSION_STYLE("genre_progression_style"),
    GENRE_CHORDS_PER_BAR("genre_chords_per_bar"),
    PROGRESSION_ANCHOR("progression_anchor"),
    PROGRESSION_DRIFT_RANGE("progression_drift_range"),
    // Custom chord matrix: pushed via "chord_matrix_active" + "chord_matrix_N" (N=0..48)
    // Soloist matrix: pushed via "soloist_matrix_active" + "soloist_matrix_N" (N=0..63)
    // Both use dynamic PluginControlId strings, no enum entries needed

    // ── Tension profile ──
    TENSION_INNER_BARS("tension_inner_bars"),
    TENSION_OUTER_BARS("tension_outer_bars"),
    TENSION_OUTER_DEPTH("tension_outer_depth"),
    TENSION_VOLUME("tension_volume"),
    TENSION_TIMING("tension_timing"),
    // Tonal tension
    TENSION_OCTAVE_SHIFT("tension_octave_shift"),
    TENSION_KEY_SHIFT("tension_key_shift"),
    TENSION_HALF_LICK("tension_half_lick"),
    TENSION_CHROMATIC_PASSING("tension_chromatic_passing"),
    // Evolution tension
    TENSION_EVO_TIMBRE_LOW("tension_evo_timbre_low"),
    TENSION_EVO_TIMBRE_HIGH("tension_evo_timbre_high"),
    TENSION_EVO_TIMBRE_PROB("tension_evo_timbre_prob"),
    TENSION_EVO_MORPH_LOW("tension_evo_morph_low"),
    TENSION_EVO_MORPH_HIGH("tension_evo_morph_high"),
    TENSION_EVO_MORPH_PROB("tension_evo_morph_prob"),
    TENSION_EVO_HARM_LOW("tension_evo_harm_low"),
    TENSION_EVO_HARM_HIGH("tension_evo_harm_high"),
    TENSION_EVO_HARM_PROB("tension_evo_harm_prob"),
    TENSION_EVO_ATTACK_POINT("tension_evo_attack_point"),
    TENSION_EVO_RELEASE_SPEED("tension_evo_release_speed"),
    TENSION_SPURT_CHANCE("tension_spurt_chance"),
    // Per-track evolution weight
    TRACK_0_EVO_WEIGHT("track_0_evo_weight"),
    TRACK_1_EVO_WEIGHT("track_1_evo_weight"),
    TRACK_2_EVO_WEIGHT("track_2_evo_weight"),
    TRACK_3_EVO_WEIGHT("track_3_evo_weight"),
    TRACK_4_EVO_WEIGHT("track_4_evo_weight"),
    TRACK_5_EVO_WEIGHT("track_5_evo_weight"),
    TRACK_6_EVO_WEIGHT("track_6_evo_weight"),
    TRACK_7_EVO_WEIGHT("track_7_evo_weight"),

    // ── Arrangement / Sections ──
    ARRANGEMENT_ACTIVE("arrangement_active"),
    ARRANGEMENT_SECTION_COUNT("arrangement_section_count"),
    ARRANGEMENT_INTRO_INDEX("arrangement_intro_index"),
    ARRANGEMENT_OUTRO_INDEX("arrangement_outro_index"),
    SECTION_DATA_START("section_data_start"),
    SECTION_TRANSITIONS_START("section_transitions_start"),
    TRACK_SOLO_BEHAVIOR_START("track_solo_behavior_start"),
    TRACK_DUCKING_START("track_ducking_start"),
    TRACK_SOLO_MARKOV_START("track_solo_markov_start"),
    ARRANGEMENT_GENERATION("arrangement_generation"),

    // Track mute (UI toggle, not persisted)
    TRACK_0_MUTE("track_0_mute"),
    TRACK_1_MUTE("track_1_mute"),
    TRACK_2_MUTE("track_2_mute"),
    TRACK_3_MUTE("track_3_mute"),
    TRACK_4_MUTE("track_4_mute"),
    TRACK_5_MUTE("track_5_mute"),
    TRACK_6_MUTE("track_6_mute"),
    TRACK_7_MUTE("track_7_mute"),

    // Per-track mod LFO parameters
    TRACK_0_MOD_LFO_RATE("track_0_mod_lfo_rate"),
    TRACK_1_MOD_LFO_RATE("track_1_mod_lfo_rate"),
    TRACK_2_MOD_LFO_RATE("track_2_mod_lfo_rate"),
    TRACK_3_MOD_LFO_RATE("track_3_mod_lfo_rate"),
    TRACK_4_MOD_LFO_RATE("track_4_mod_lfo_rate"),
    TRACK_5_MOD_LFO_RATE("track_5_mod_lfo_rate"),
    TRACK_6_MOD_LFO_RATE("track_6_mod_lfo_rate"),
    TRACK_7_MOD_LFO_RATE("track_7_mod_lfo_rate"),
    TRACK_0_MOD_LFO_DEPTH("track_0_mod_lfo_depth"),
    TRACK_1_MOD_LFO_DEPTH("track_1_mod_lfo_depth"),
    TRACK_2_MOD_LFO_DEPTH("track_2_mod_lfo_depth"),
    TRACK_3_MOD_LFO_DEPTH("track_3_mod_lfo_depth"),
    TRACK_4_MOD_LFO_DEPTH("track_4_mod_lfo_depth"),
    TRACK_5_MOD_LFO_DEPTH("track_5_mod_lfo_depth"),
    TRACK_6_MOD_LFO_DEPTH("track_6_mod_lfo_depth"),
    TRACK_7_MOD_LFO_DEPTH("track_7_mod_lfo_depth"),
    TRACK_0_MOD_LFO_SHAPE("track_0_mod_lfo_shape"),
    TRACK_1_MOD_LFO_SHAPE("track_1_mod_lfo_shape"),
    TRACK_2_MOD_LFO_SHAPE("track_2_mod_lfo_shape"),
    TRACK_3_MOD_LFO_SHAPE("track_3_mod_lfo_shape"),
    TRACK_4_MOD_LFO_SHAPE("track_4_mod_lfo_shape"),
    TRACK_5_MOD_LFO_SHAPE("track_5_mod_lfo_shape"),
    TRACK_6_MOD_LFO_SHAPE("track_6_mod_lfo_shape"),
    TRACK_7_MOD_LFO_SHAPE("track_7_mod_lfo_shape"),
    TRACK_0_MOD_LFO_COUPLING("track_0_mod_lfo_coupling"),
    TRACK_1_MOD_LFO_COUPLING("track_1_mod_lfo_coupling"),
    TRACK_2_MOD_LFO_COUPLING("track_2_mod_lfo_coupling"),
    TRACK_3_MOD_LFO_COUPLING("track_3_mod_lfo_coupling"),
    TRACK_4_MOD_LFO_COUPLING("track_4_mod_lfo_coupling"),
    TRACK_5_MOD_LFO_COUPLING("track_5_mod_lfo_coupling"),
    TRACK_6_MOD_LFO_COUPLING("track_6_mod_lfo_coupling"),
    TRACK_7_MOD_LFO_COUPLING("track_7_mod_lfo_coupling"),

    // Per-track hold parameters
    TRACK_0_HOLD_PROBABILITY("track_0_hold_probability"),
    TRACK_1_HOLD_PROBABILITY("track_1_hold_probability"),
    TRACK_2_HOLD_PROBABILITY("track_2_hold_probability"),
    TRACK_3_HOLD_PROBABILITY("track_3_hold_probability"),
    TRACK_4_HOLD_PROBABILITY("track_4_hold_probability"),
    TRACK_5_HOLD_PROBABILITY("track_5_hold_probability"),
    TRACK_6_HOLD_PROBABILITY("track_6_hold_probability"),
    TRACK_7_HOLD_PROBABILITY("track_7_hold_probability"),
    TRACK_0_HOLD_LENGTH_MIN("track_0_hold_length_min"),
    TRACK_1_HOLD_LENGTH_MIN("track_1_hold_length_min"),
    TRACK_2_HOLD_LENGTH_MIN("track_2_hold_length_min"),
    TRACK_3_HOLD_LENGTH_MIN("track_3_hold_length_min"),
    TRACK_4_HOLD_LENGTH_MIN("track_4_hold_length_min"),
    TRACK_5_HOLD_LENGTH_MIN("track_5_hold_length_min"),
    TRACK_6_HOLD_LENGTH_MIN("track_6_hold_length_min"),
    TRACK_7_HOLD_LENGTH_MIN("track_7_hold_length_min"),
    TRACK_0_HOLD_LENGTH_MAX("track_0_hold_length_max"),
    TRACK_1_HOLD_LENGTH_MAX("track_1_hold_length_max"),
    TRACK_2_HOLD_LENGTH_MAX("track_2_hold_length_max"),
    TRACK_3_HOLD_LENGTH_MAX("track_3_hold_length_max"),
    TRACK_4_HOLD_LENGTH_MAX("track_4_hold_length_max"),
    TRACK_5_HOLD_LENGTH_MAX("track_5_hold_length_max"),
    TRACK_6_HOLD_LENGTH_MAX("track_6_hold_length_max"),
    TRACK_7_HOLD_LENGTH_MAX("track_7_hold_length_max"),

    // Per-track effect sends
    TRACK_0_DELAY_SEND("track_0_delay_send"),
    TRACK_1_DELAY_SEND("track_1_delay_send"),
    TRACK_2_DELAY_SEND("track_2_delay_send"),
    TRACK_3_DELAY_SEND("track_3_delay_send"),
    TRACK_4_DELAY_SEND("track_4_delay_send"),
    TRACK_5_DELAY_SEND("track_5_delay_send"),
    TRACK_6_DELAY_SEND("track_6_delay_send"),
    TRACK_7_DELAY_SEND("track_7_delay_send"),
    TRACK_0_REVERB_SEND_TRACK("track_0_reverb_send"),
    TRACK_1_REVERB_SEND_TRACK("track_1_reverb_send"),
    TRACK_2_REVERB_SEND_TRACK("track_2_reverb_send"),
    TRACK_3_REVERB_SEND_TRACK("track_3_reverb_send"),
    TRACK_4_REVERB_SEND_TRACK("track_4_reverb_send"),
    TRACK_5_REVERB_SEND_TRACK("track_5_reverb_send"),
    TRACK_6_REVERB_SEND_TRACK("track_6_reverb_send"),
    TRACK_7_REVERB_SEND_TRACK("track_7_reverb_send"),

    // Per-track note range
    TRACK_0_NOTE_RANGE_LOW("track_0_note_range_low"),
    TRACK_1_NOTE_RANGE_LOW("track_1_note_range_low"),
    TRACK_2_NOTE_RANGE_LOW("track_2_note_range_low"),
    TRACK_3_NOTE_RANGE_LOW("track_3_note_range_low"),
    TRACK_4_NOTE_RANGE_LOW("track_4_note_range_low"),
    TRACK_5_NOTE_RANGE_LOW("track_5_note_range_low"),
    TRACK_6_NOTE_RANGE_LOW("track_6_note_range_low"),
    TRACK_7_NOTE_RANGE_LOW("track_7_note_range_low"),
    TRACK_0_NOTE_RANGE_HIGH("track_0_note_range_high"),
    TRACK_1_NOTE_RANGE_HIGH("track_1_note_range_high"),
    TRACK_2_NOTE_RANGE_HIGH("track_2_note_range_high"),
    TRACK_3_NOTE_RANGE_HIGH("track_3_note_range_high"),
    TRACK_4_NOTE_RANGE_HIGH("track_4_note_range_high"),
    TRACK_5_NOTE_RANGE_HIGH("track_5_note_range_high"),
    TRACK_6_NOTE_RANGE_HIGH("track_6_note_range_high"),
    TRACK_7_NOTE_RANGE_HIGH("track_7_note_range_high"),
    TRACK_0_REVERB_BRIGHTNESS("track_0_reverb_brightness"),
    TRACK_1_REVERB_BRIGHTNESS("track_1_reverb_brightness"),
    TRACK_2_REVERB_BRIGHTNESS("track_2_reverb_brightness"),
    TRACK_3_REVERB_BRIGHTNESS("track_3_reverb_brightness"),
    TRACK_4_REVERB_BRIGHTNESS("track_4_reverb_brightness"),
    TRACK_5_REVERB_BRIGHTNESS("track_5_reverb_brightness"),
    TRACK_6_REVERB_BRIGHTNESS("track_6_reverb_brightness"),
    TRACK_7_REVERB_BRIGHTNESS("track_7_reverb_brightness"),
    TRACK_0_DENSITY_OVERRIDE("track_0_density_override"),
    TRACK_1_DENSITY_OVERRIDE("track_1_density_override"),
    TRACK_2_DENSITY_OVERRIDE("track_2_density_override"),
    TRACK_3_DENSITY_OVERRIDE("track_3_density_override"),
    TRACK_4_DENSITY_OVERRIDE("track_4_density_override"),
    TRACK_5_DENSITY_OVERRIDE("track_5_density_override"),
    TRACK_6_DENSITY_OVERRIDE("track_6_density_override"),
    TRACK_7_DENSITY_OVERRIDE("track_7_density_override"),
    TRACK_0_DELAY_FEEDBACK_TRACK("track_0_delay_feedback"),
    TRACK_1_DELAY_FEEDBACK_TRACK("track_1_delay_feedback"),
    TRACK_2_DELAY_FEEDBACK_TRACK("track_2_delay_feedback"),
    TRACK_3_DELAY_FEEDBACK_TRACK("track_3_delay_feedback"),
    TRACK_4_DELAY_FEEDBACK_TRACK("track_4_delay_feedback"),
    TRACK_5_DELAY_FEEDBACK_TRACK("track_5_delay_feedback"),
    TRACK_6_DELAY_FEEDBACK_TRACK("track_6_delay_feedback"),
    TRACK_7_DELAY_FEEDBACK_TRACK("track_7_delay_feedback"),
    TRACK_0_GLIDE_RATE("track_0_glide_rate"),
    TRACK_1_GLIDE_RATE("track_1_glide_rate"),
    TRACK_2_GLIDE_RATE("track_2_glide_rate"),
    TRACK_3_GLIDE_RATE("track_3_glide_rate"),
    TRACK_4_GLIDE_RATE("track_4_glide_rate"),
    TRACK_5_GLIDE_RATE("track_5_glide_rate"),
    TRACK_6_GLIDE_RATE("track_6_glide_rate"),
    TRACK_7_GLIDE_RATE("track_7_glide_rate"),
    // Per-track lick mode: 0=NONE, 1=SQUASH, 2=FILL
    TRACK_0_LICK_MODE("track_0_lick_mode"),
    TRACK_1_LICK_MODE("track_1_lick_mode"),
    TRACK_2_LICK_MODE("track_2_lick_mode"),
    TRACK_3_LICK_MODE("track_3_lick_mode"),
    TRACK_4_LICK_MODE("track_4_lick_mode"),
    TRACK_5_LICK_MODE("track_5_lick_mode"),
    TRACK_6_LICK_MODE("track_6_lick_mode"),
    TRACK_7_LICK_MODE("track_7_lick_mode"),
    // Per-track evolution: tension response (float 0-1)
    TRACK_0_EVO_TENSION_RESP("track_0_evo_tension_resp"),
    TRACK_1_EVO_TENSION_RESP("track_1_evo_tension_resp"),
    TRACK_2_EVO_TENSION_RESP("track_2_evo_tension_resp"),
    TRACK_3_EVO_TENSION_RESP("track_3_evo_tension_resp"),
    TRACK_4_EVO_TENSION_RESP("track_4_evo_tension_resp"),
    TRACK_5_EVO_TENSION_RESP("track_5_evo_tension_resp"),
    TRACK_6_EVO_TENSION_RESP("track_6_evo_tension_resp"),
    TRACK_7_EVO_TENSION_RESP("track_7_evo_tension_resp"),
    // Per-track evolution: note follow mode (int 0=SLIDE, 1=CONTOUR, 2=BLEND)
    TRACK_0_EVO_NOTE_FOLLOW("track_0_evo_note_follow"),
    TRACK_1_EVO_NOTE_FOLLOW("track_1_evo_note_follow"),
    TRACK_2_EVO_NOTE_FOLLOW("track_2_evo_note_follow"),
    TRACK_3_EVO_NOTE_FOLLOW("track_3_evo_note_follow"),
    TRACK_4_EVO_NOTE_FOLLOW("track_4_evo_note_follow"),
    TRACK_5_EVO_NOTE_FOLLOW("track_5_evo_note_follow"),
    TRACK_6_EVO_NOTE_FOLLOW("track_6_evo_note_follow"),
    TRACK_7_EVO_NOTE_FOLLOW("track_7_evo_note_follow"),
    // Per-track evolution: pitch mode (int 0=NONE, 1=CONTOUR, 2=VOICING)
    TRACK_0_EVO_PITCH_MODE("track_0_evo_pitch_mode"),
    TRACK_1_EVO_PITCH_MODE("track_1_evo_pitch_mode"),
    TRACK_2_EVO_PITCH_MODE("track_2_evo_pitch_mode"),
    TRACK_3_EVO_PITCH_MODE("track_3_evo_pitch_mode"),
    TRACK_4_EVO_PITCH_MODE("track_4_evo_pitch_mode"),
    TRACK_5_EVO_PITCH_MODE("track_5_evo_pitch_mode"),
    TRACK_6_EVO_PITCH_MODE("track_6_evo_pitch_mode"),
    TRACK_7_EVO_PITCH_MODE("track_7_evo_pitch_mode"),
    // Per-track evolution: voicing tension response (float 0-1, CHORDAL only)
    TRACK_0_EVO_VOICING_TENSION("track_0_evo_voicing_tension"),
    TRACK_1_EVO_VOICING_TENSION("track_1_evo_voicing_tension"),
    TRACK_2_EVO_VOICING_TENSION("track_2_evo_voicing_tension"),
    TRACK_3_EVO_VOICING_TENSION("track_3_evo_voicing_tension"),
    TRACK_4_EVO_VOICING_TENSION("track_4_evo_voicing_tension"),
    TRACK_5_EVO_VOICING_TENSION("track_5_evo_voicing_tension"),
    TRACK_6_EVO_VOICING_TENSION("track_6_evo_voicing_tension"),
    TRACK_7_EVO_VOICING_TENSION("track_7_evo_voicing_tension"),

    // Per-track comping style: int-encoded CompingStyle (0=PAD, 1=FUNK_STABS, 2=ROCK_DOWNBEATS, 3=CUSTOM)
    TRACK_0_COMPING_STYLE("track_0_comping_style"),
    TRACK_1_COMPING_STYLE("track_1_comping_style"),
    TRACK_2_COMPING_STYLE("track_2_comping_style"),
    TRACK_3_COMPING_STYLE("track_3_comping_style"),
    TRACK_4_COMPING_STYLE("track_4_comping_style"),
    TRACK_5_COMPING_STYLE("track_5_comping_style"),
    TRACK_6_COMPING_STYLE("track_6_comping_style"),
    TRACK_7_COMPING_STYLE("track_7_comping_style"),
    // Per-track arp mode: int (0=AUTO, 1=ALWAYS, 2=NEVER)
    TRACK_0_ARP_MODE("track_0_arp_mode"),
    TRACK_1_ARP_MODE("track_1_arp_mode"),
    TRACK_2_ARP_MODE("track_2_arp_mode"),
    TRACK_3_ARP_MODE("track_3_arp_mode"),
    TRACK_4_ARP_MODE("track_4_arp_mode"),
    TRACK_5_ARP_MODE("track_5_arp_mode"),
    TRACK_6_ARP_MODE("track_6_arp_mode"),
    TRACK_7_ARP_MODE("track_7_arp_mode"),
    // Per-track arp speed: float 0-1
    TRACK_0_ARP_SPEED("track_0_arp_speed"),
    TRACK_1_ARP_SPEED("track_1_arp_speed"),
    TRACK_2_ARP_SPEED("track_2_arp_speed"),
    TRACK_3_ARP_SPEED("track_3_arp_speed"),
    TRACK_4_ARP_SPEED("track_4_arp_speed"),
    TRACK_5_ARP_SPEED("track_5_arp_speed"),
    TRACK_6_ARP_SPEED("track_6_arp_speed"),
    TRACK_7_ARP_SPEED("track_7_arp_speed"),
    // Per-track arp direction: int (0=UP, 1=DOWN, 2=UP_DOWN, 3=RANDOM)
    TRACK_0_ARP_DIRECTION("track_0_arp_direction"),
    TRACK_1_ARP_DIRECTION("track_1_arp_direction"),
    TRACK_2_ARP_DIRECTION("track_2_arp_direction"),
    TRACK_3_ARP_DIRECTION("track_3_arp_direction"),
    TRACK_4_ARP_DIRECTION("track_4_arp_direction"),
    TRACK_5_ARP_DIRECTION("track_5_arp_direction"),
    TRACK_6_ARP_DIRECTION("track_6_arp_direction"),
    TRACK_7_ARP_DIRECTION("track_7_arp_direction"),

    // Per-track humanization: drop/ghost/octave/extension probabilities (float 0-1)
    TRACK_0_HUMAN_DROP_PROB("track_0_human_drop_prob"),
    TRACK_1_HUMAN_DROP_PROB("track_1_human_drop_prob"),
    TRACK_2_HUMAN_DROP_PROB("track_2_human_drop_prob"),
    TRACK_3_HUMAN_DROP_PROB("track_3_human_drop_prob"),
    TRACK_4_HUMAN_DROP_PROB("track_4_human_drop_prob"),
    TRACK_5_HUMAN_DROP_PROB("track_5_human_drop_prob"),
    TRACK_6_HUMAN_DROP_PROB("track_6_human_drop_prob"),
    TRACK_7_HUMAN_DROP_PROB("track_7_human_drop_prob"),
    TRACK_0_HUMAN_GHOST_PROB("track_0_human_ghost_prob"),
    TRACK_1_HUMAN_GHOST_PROB("track_1_human_ghost_prob"),
    TRACK_2_HUMAN_GHOST_PROB("track_2_human_ghost_prob"),
    TRACK_3_HUMAN_GHOST_PROB("track_3_human_ghost_prob"),
    TRACK_4_HUMAN_GHOST_PROB("track_4_human_ghost_prob"),
    TRACK_5_HUMAN_GHOST_PROB("track_5_human_ghost_prob"),
    TRACK_6_HUMAN_GHOST_PROB("track_6_human_ghost_prob"),
    TRACK_7_HUMAN_GHOST_PROB("track_7_human_ghost_prob"),
    TRACK_0_HUMAN_OCTAVE_PROB("track_0_human_octave_prob"),
    TRACK_1_HUMAN_OCTAVE_PROB("track_1_human_octave_prob"),
    TRACK_2_HUMAN_OCTAVE_PROB("track_2_human_octave_prob"),
    TRACK_3_HUMAN_OCTAVE_PROB("track_3_human_octave_prob"),
    TRACK_4_HUMAN_OCTAVE_PROB("track_4_human_octave_prob"),
    TRACK_5_HUMAN_OCTAVE_PROB("track_5_human_octave_prob"),
    TRACK_6_HUMAN_OCTAVE_PROB("track_6_human_octave_prob"),
    TRACK_7_HUMAN_OCTAVE_PROB("track_7_human_octave_prob"),
    TRACK_0_HUMAN_EXT_PROB("track_0_human_ext_prob"),
    TRACK_1_HUMAN_EXT_PROB("track_1_human_ext_prob"),
    TRACK_2_HUMAN_EXT_PROB("track_2_human_ext_prob"),
    TRACK_3_HUMAN_EXT_PROB("track_3_human_ext_prob"),
    TRACK_4_HUMAN_EXT_PROB("track_4_human_ext_prob"),
    TRACK_5_HUMAN_EXT_PROB("track_5_human_ext_prob"),
    TRACK_6_HUMAN_EXT_PROB("track_6_human_ext_prob"),
    TRACK_7_HUMAN_EXT_PROB("track_7_human_ext_prob"),

    TRACK_0_FILL_EVERY_N("track_0_fill_every_n"),
    TRACK_1_FILL_EVERY_N("track_1_fill_every_n"),
    TRACK_2_FILL_EVERY_N("track_2_fill_every_n"),
    TRACK_3_FILL_EVERY_N("track_3_fill_every_n"),
    TRACK_4_FILL_EVERY_N("track_4_fill_every_n"),
    TRACK_5_FILL_EVERY_N("track_5_fill_every_n"),
    TRACK_6_FILL_EVERY_N("track_6_fill_every_n"),
    TRACK_7_FILL_EVERY_N("track_7_fill_every_n"),
    TRACK_0_FILL_TYPE("track_0_fill_type"),
    TRACK_1_FILL_TYPE("track_1_fill_type"),
    TRACK_2_FILL_TYPE("track_2_fill_type"),
    TRACK_3_FILL_TYPE("track_3_fill_type"),
    TRACK_4_FILL_TYPE("track_4_fill_type"),
    TRACK_5_FILL_TYPE("track_5_fill_type"),
    TRACK_6_FILL_TYPE("track_6_fill_type"),
    TRACK_7_FILL_TYPE("track_7_fill_type"),
    TRACK_0_FILL_SKIP_PROB("track_0_fill_skip_prob"),
    TRACK_1_FILL_SKIP_PROB("track_1_fill_skip_prob"),
    TRACK_2_FILL_SKIP_PROB("track_2_fill_skip_prob"),
    TRACK_3_FILL_SKIP_PROB("track_3_fill_skip_prob"),
    TRACK_4_FILL_SKIP_PROB("track_4_fill_skip_prob"),
    TRACK_5_FILL_SKIP_PROB("track_5_fill_skip_prob"),
    TRACK_6_FILL_SKIP_PROB("track_6_fill_skip_prob"),
    TRACK_7_FILL_SKIP_PROB("track_7_fill_skip_prob"),

    // Per-track section inversion: int (0=FOLLOW_STYLE, 1=ROOT, 2=FIRST, 3=SECOND, 4=OPEN)
    TRACK_0_INVERSION("track_0_inversion"),
    TRACK_1_INVERSION("track_1_inversion"),
    TRACK_2_INVERSION("track_2_inversion"),
    TRACK_3_INVERSION("track_3_inversion"),
    TRACK_4_INVERSION("track_4_inversion"),
    TRACK_5_INVERSION("track_5_inversion"),
    TRACK_6_INVERSION("track_6_inversion"),
    TRACK_7_INVERSION("track_7_inversion"),

    // Per-track chord follow mode: int (0=FOLLOW, 1=ROOT_ONLY, 2=FIXED)
    TRACK_0_CHORD_FOLLOW("track_0_chord_follow"),
    TRACK_1_CHORD_FOLLOW("track_1_chord_follow"),
    TRACK_2_CHORD_FOLLOW("track_2_chord_follow"),
    TRACK_3_CHORD_FOLLOW("track_3_chord_follow"),
    TRACK_4_CHORD_FOLLOW("track_4_chord_follow"),
    TRACK_5_CHORD_FOLLOW("track_5_chord_follow"),
    TRACK_6_CHORD_FOLLOW("track_6_chord_follow"),
    TRACK_7_CHORD_FOLLOW("track_7_chord_follow"),

    // Per-track LPG mode (applies on the EDM engine slot):
    //   int LpgMode (0=BYPASS, 1=SUSTAINED, 2=PLUCK, 3=ENGINE_DEFAULT)
    TRACK_0_LPG_MODE("track_0_lpg_mode"),
    TRACK_1_LPG_MODE("track_1_lpg_mode"),
    TRACK_2_LPG_MODE("track_2_lpg_mode"),
    TRACK_3_LPG_MODE("track_3_lpg_mode"),
    TRACK_4_LPG_MODE("track_4_lpg_mode"),
    TRACK_5_LPG_MODE("track_5_lpg_mode"),
    TRACK_6_LPG_MODE("track_6_lpg_mode"),
    TRACK_7_LPG_MODE("track_7_lpg_mode"),
    // Per-track LPG mode for the SPACE engine slot (Kotlin pushes
    // lpgModeSpace ?: lpgMode so a single explicit lpgMode covers both slots).
    TRACK_0_LPG_MODE_SPACE("track_0_lpg_mode_space"),
    TRACK_1_LPG_MODE_SPACE("track_1_lpg_mode_space"),
    TRACK_2_LPG_MODE_SPACE("track_2_lpg_mode_space"),
    TRACK_3_LPG_MODE_SPACE("track_3_lpg_mode_space"),
    TRACK_4_LPG_MODE_SPACE("track_4_lpg_mode_space"),
    TRACK_5_LPG_MODE_SPACE("track_5_lpg_mode_space"),
    TRACK_6_LPG_MODE_SPACE("track_6_lpg_mode_space"),
    TRACK_7_LPG_MODE_SPACE("track_7_lpg_mode_space"),
    // Per-track LPG decay (vactrol tail length): float 0-1
    TRACK_0_LPG_DECAY("track_0_lpg_decay"),
    TRACK_1_LPG_DECAY("track_1_lpg_decay"),
    TRACK_2_LPG_DECAY("track_2_lpg_decay"),
    TRACK_3_LPG_DECAY("track_3_lpg_decay"),
    TRACK_4_LPG_DECAY("track_4_lpg_decay"),
    TRACK_5_LPG_DECAY("track_5_lpg_decay"),
    TRACK_6_LPG_DECAY("track_6_lpg_decay"),
    TRACK_7_LPG_DECAY("track_7_lpg_decay"),
    // Per-track LPG colour (HF bleed): float 0-1
    TRACK_0_LPG_COLOUR("track_0_lpg_colour"),
    TRACK_1_LPG_COLOUR("track_1_lpg_colour"),
    TRACK_2_LPG_COLOUR("track_2_lpg_colour"),
    TRACK_3_LPG_COLOUR("track_3_lpg_colour"),
    TRACK_4_LPG_COLOUR("track_4_lpg_colour"),
    TRACK_5_LPG_COLOUR("track_5_lpg_colour"),
    TRACK_6_LPG_COLOUR("track_6_lpg_colour"),
    TRACK_7_LPG_COLOUR("track_7_lpg_colour"),

    // Pulsar dedicated effect parameters (pushed on vibe change)
    PULSAR_DELAY_TIME_A("pulsar_delay_time_a"),
    PULSAR_DELAY_TIME_B("pulsar_delay_time_b"),
    PULSAR_DELAY_FEEDBACK("pulsar_delay_feedback"),
    PULSAR_DELAY_DAMPING("pulsar_delay_damping"),
    PULSAR_REVERB_SIZE("pulsar_reverb_size"),
    PULSAR_REVERB_DAMPING("pulsar_reverb_damping"),
    PULSAR_REVERB_BRIGHTNESS("pulsar_reverb_brightness"),
}
