package org.balch.orpheus.features.pulsar.vibes

import dev.zacsweers.metro.ContributesIntoSet
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.binding
import kotlin.String
import org.balch.orpheus.core.audio.OrpheusEngineId
import org.balch.orpheus.core.di.FeatureScope
import org.balch.orpheus.features.pulsar.models.Album
import org.balch.orpheus.features.pulsar.models.ArpDirection
import org.balch.orpheus.features.pulsar.models.ArpMode
import org.balch.orpheus.features.pulsar.models.Arrangement
import org.balch.orpheus.features.pulsar.models.Band
import org.balch.orpheus.features.pulsar.models.BandMember
import org.balch.orpheus.features.pulsar.models.BarStrategy
import org.balch.orpheus.features.pulsar.models.ChordComping
import org.balch.orpheus.features.pulsar.models.ChordFollow
import org.balch.orpheus.features.pulsar.models.ChordStep
import org.balch.orpheus.features.pulsar.models.CompingFills
import org.balch.orpheus.features.pulsar.models.CompingHumanization
import org.balch.orpheus.features.pulsar.models.CompingStyle
import org.balch.orpheus.features.pulsar.models.EnvelopeProfile
import org.balch.orpheus.features.pulsar.models.EnvelopeType
import org.balch.orpheus.features.pulsar.models.Evolution
import org.balch.orpheus.features.pulsar.models.EvolutionTension
import org.balch.orpheus.features.pulsar.models.FillType
import org.balch.orpheus.features.pulsar.models.GenreProfile
import org.balch.orpheus.features.pulsar.models.HalfLick
import org.balch.orpheus.features.pulsar.models.Lick
import org.balch.orpheus.features.pulsar.models.LickMode
import org.balch.orpheus.features.pulsar.models.LickSource
import org.balch.orpheus.features.pulsar.models.LickStep
import org.balch.orpheus.features.pulsar.models.LpgMode
import org.balch.orpheus.features.pulsar.models.MacroOverrides
import org.balch.orpheus.features.pulsar.models.MacroSource
import org.balch.orpheus.features.pulsar.models.MacroTarget
import org.balch.orpheus.features.pulsar.models.OrpheusEngine
import org.balch.orpheus.features.pulsar.models.ProgressionAnchor
import org.balch.orpheus.features.pulsar.models.ProgressionStyle
import org.balch.orpheus.features.pulsar.models.RootNote
import org.balch.orpheus.features.pulsar.models.ScaleType
import org.balch.orpheus.features.pulsar.models.Section
import org.balch.orpheus.features.pulsar.models.SectionInversion
import org.balch.orpheus.features.pulsar.models.SectionTransition
import org.balch.orpheus.features.pulsar.models.SoloMode
import org.balch.orpheus.features.pulsar.models.TensionProfile
import org.balch.orpheus.features.pulsar.models.TonalTension
import org.balch.orpheus.features.pulsar.models.TrackMacroMap
import org.balch.orpheus.features.pulsar.models.TrackRole
import org.balch.orpheus.features.pulsar.models.TrackSectionOverride
import org.balch.orpheus.features.pulsar.models.TrackVoice
import org.balch.orpheus.features.pulsar.models.Vibe
import org.balch.orpheus.features.pulsar.models.VibeEffects
import org.balch.orpheus.features.pulsar.models.VibeProvider

/**
 * Bricklayer's Lament — generated from an AI-archived vibe JSON by tools:vibe-codegen (NOT hand-authored).
 * A compiling, faithful starting point; polish (idiom collapsing, musical notes, tuning)
 * via the vibe-creator skill once this vibe earns a permanent keep.
 */
@Inject
@ContributesIntoSet(FeatureScope::class, binding = binding<VibeProvider>())
public class BricklayerSLamentVibe : VibeProvider {
  override val name: String = "Bricklayer's Lament"

  override val vibe: Vibe by lazy {
      Vibe(
        name = "Bricklayer's Lament",
        album = Album.RIF,
        tracks = listOf(
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.BD,
              volume = 0.82f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.BD,
              volume = 0.82f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Percussive,
            pan = 0.0f,
            density = 0.42f,
            envelopeProfile = EnvelopeProfile.RHYTHM,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.7f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.SD,
              volume = 0.7f,
              harmonics = 0.4f,
              timbre = 0.55f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.2f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.SD,
              volume = 0.7f,
              harmonics = 0.4f,
              timbre = 0.55f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.2f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Percussive,
            pan = -0.1f,
            density = 0.32f,
            envelopeProfile = EnvelopeProfile.RHYTHM,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.7f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
            ),
            barStrategy = BarStrategy.FILL,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.HH,
              volume = 0.5f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.HH,
              volume = 0.5f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Percussive,
            pan = 0.15f,
            density = 0.55f,
            envelopeProfile = EnvelopeProfile.RHYTHM,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.7f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.WSH,
              volume = 0.75f,
              harmonics = 0.42f,
              timbre = 0.48f,
              morph = 0.4f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.15f,
              reverbSend = 0.1f,
              noteRangeLow = 33,
              noteRangeHigh = 52,
              reverbBrightness = 0.35f,
              delayFeedback = null,
              glideRate = 0.05f,
              lpgMode = LpgMode.PLUCK,
              lpgDecay = 0.55f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.WSH,
              volume = 0.7f,
              harmonics = 0.42f,
              timbre = 0.4f,
              morph = 0.4f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.35f,
              reverbSend = 0.35f,
              noteRangeLow = 33,
              noteRangeHigh = 52,
              reverbBrightness = 0.4f,
              delayFeedback = null,
              glideRate = 0.05f,
              lpgMode = LpgMode.PLUCK,
              lpgDecay = 0.55f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.ROOT_ONLY,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.0f,
            density = 0.2f,
            envelopeProfile = EnvelopeProfile.MELODIC,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.9f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.3f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.DX2,
              volume = 0.78f,
              harmonics = 0.4596f,
              timbre = 0.5f,
              morph = 0.55f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.1f,
              reverbSend = 0.25f,
              noteRangeLow = 48,
              noteRangeHigh = 78,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.PLUCK,
              lpgDecay = 0.35f,
              lpgColour = 0.45f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.COMPLEXITY,
              harmonicsMacroRange = 0.04f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.DX2,
              volume = 0.78f,
              harmonics = 0.4596f,
              timbre = 0.25f,
              morph = 0.55f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.1f,
              reverbSend = 0.75f,
              noteRangeLow = 48,
              noteRangeHigh = 78,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.BYPASS,
              lpgDecay = 0.35f,
              lpgColour = 0.45f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.COMPLEXITY,
              harmonicsMacroRange = 0.04f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.FOLLOW,
              lickMode = LickMode.Fill,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.2f,
            density = 0.3f,
            envelopeProfile = EnvelopeProfile.MELODIC,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.9f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.3f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.PAR,
              volume = 0.45f,
              harmonics = 1.0f,
              timbre = 0.5f,
              morph = 1.0f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.25f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.75f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = true,
              pinTimbre = true,
              pinMorph = true,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.PAR,
              volume = 0.45f,
              harmonics = 1.0f,
              timbre = 0.5f,
              morph = 1.0f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.25f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.75f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = true,
              pinTimbre = true,
              pinMorph = true,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Chordal(
              comping = ChordComping(
                style = CompingStyle.PAD,
                arpMode = ArpMode.AUTO,
                arpSpeed = 0.2f,
                arpDirection = ArpDirection.UP,
                sectionInversion = SectionInversion.FOLLOW_STYLE,
                humanization = CompingHumanization(
                  dropProbability = 0.0f,
                  ghostProbability = 0.0f,
                  octaveJumpProbability = 0.0f,
                  extensionProbability = 0.0f,
                ),
                fills = CompingFills(
                  everyNBars = 0,
                  fillType = FillType.ASCENDING_ARP,
                  skipProbability = 0.0f,
                ),
              ),
              chordFollow = ChordFollow.ROOT_ONLY,
            ),
            pan = -0.25f,
            density = 0.42f,
            envelopeProfile = EnvelopeProfile.EFFECT,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.7f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.DX3,
              volume = 0.35f,
              harmonics = 0.5668f,
              timbre = 0.72f,
              morph = 0.55f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.15f,
              reverbSend = 0.3f,
              noteRangeLow = 50,
              noteRangeHigh = 74,
              reverbBrightness = 0.45f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.DX3,
              volume = 0.45f,
              harmonics = 0.5668f,
              timbre = 0.6f,
              morph = 0.55f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.35f,
              reverbSend = 0.6f,
              noteRangeLow = 50,
              noteRangeHigh = 74,
              reverbBrightness = 0.6f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Chordal(
              comping = ChordComping(
                style = CompingStyle.ROCK_DOWNBEATS,
                arpMode = ArpMode.AUTO,
                arpSpeed = 0.2f,
                arpDirection = ArpDirection.UP,
                sectionInversion = SectionInversion.FOLLOW_STYLE,
                humanization = CompingHumanization(
                  dropProbability = 0.15f,
                  ghostProbability = 0.1f,
                  octaveJumpProbability = 0.1f,
                  extensionProbability = 0.0f,
                ),
                fills = CompingFills(
                  everyNBars = 0,
                  fillType = FillType.ASCENDING_ARP,
                  skipProbability = 0.0f,
                ),
              ),
              chordFollow = ChordFollow.FOLLOW,
            ),
            pan = -0.2f,
            density = 0.2f,
            envelopeProfile = EnvelopeProfile.MELODIC,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.9f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.3f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.STR,
              volume = 0.4f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.08f,
              modLfoDepth = 0.5f,
              modLfoShape = 0.4f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.7f,
              holdLengthMin = 4,
              holdLengthMax = 12,
              delaySend = 0.25f,
              reverbSend = 0.55f,
              noteRangeLow = 48,
              noteRangeHigh = 67,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.45f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.STR,
              volume = 0.4f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.08f,
              modLfoDepth = 0.5f,
              modLfoShape = 0.4f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.7f,
              holdLengthMin = 4,
              holdLengthMax = 12,
              delaySend = 0.25f,
              reverbSend = 0.55f,
              noteRangeLow = 48,
              noteRangeHigh = 67,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.45f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Chordal(
              comping = ChordComping(
                style = CompingStyle.PAD,
                arpMode = ArpMode.AUTO,
                arpSpeed = 0.2f,
                arpDirection = ArpDirection.UP,
                sectionInversion = SectionInversion.FOLLOW_STYLE,
                humanization = CompingHumanization(
                  dropProbability = 0.0f,
                  ghostProbability = 0.0f,
                  octaveJumpProbability = 0.0f,
                  extensionProbability = 0.0f,
                ),
                fills = CompingFills(
                  everyNBars = 0,
                  fillType = FillType.ASCENDING_ARP,
                  skipProbability = 0.0f,
                ),
              ),
              chordFollow = ChordFollow.FOLLOW,
            ),
            pan = 0.3f,
            density = 0.1f,
            envelopeProfile = EnvelopeProfile.EFFECT,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              energyDensity = MacroTarget(
                min = 0.05f,
                max = 0.25f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.2f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.25f,
              ),
              spaceDecay = MacroTarget(
                min = 0.5f,
                max = 0.9f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.INDEPENDENT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
        ),
        lick = Lick(
          steps = listOf(
            LickStep(
              scaleDegree = 0,
              duration = 1.0f,
              velocity = 0.95f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 2,
              duration = 0.5f,
              velocity = 0.9f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 3,
              duration = 0.5f,
              velocity = 0.85f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 1.0f,
              velocity = 0.95f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 0,
              duration = 0.5f,
              velocity = 0.9f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 0,
              duration = 0.5f,
              velocity = 0.85f,
              glideRate = -1.0f,
            ),
          ),
          loopLength = 0,
        ),
        lickMutation = 0.35f,
        lickOctave = -1,
        lickRotation = null,
        bassLine = null,
        bassLineMutation = 0.5f,
        bassLineOctave = -1,
        band = Band(
          members = listOf(
            BandMember(
              name = "Drums",
              tracks = listOf(
                0,
                1,
                2,
              ),
              alwaysActive = true,
              loudness = 0.5f,
              creativity = 0.2f,
              swing = 0.0f,
              drag = 0.0f,
            ),
            BandMember(
              name = "Bass",
              tracks = listOf(
                3,
              ),
              alwaysActive = false,
              loudness = 0.5f,
              creativity = 0.25f,
              swing = 0.0f,
              drag = 0.0f,
            ),
            BandMember(
              name = "Piano",
              tracks = listOf(
                4,
                5,
              ),
              alwaysActive = false,
              loudness = 0.5f,
              creativity = 0.4f,
              swing = 0.0f,
              drag = 0.0f,
            ),
            BandMember(
              name = "SaxSlide",
              tracks = listOf(
                6,
                7,
              ),
              alwaysActive = false,
              loudness = 0.55f,
              creativity = 0.4f,
              swing = 0.0f,
              drag = 0.0f,
            ),
          ),
          handoffMatrix = listOf(
            0.0f,
            0.3f,
            0.55f,
            0.15f,
            0.1f,
            0.0f,
            0.65f,
            0.25f,
            0.1f,
            0.3f,
            0.0f,
            0.6f,
            0.1f,
            0.3f,
            0.6f,
            0.0f,
          ),
          pullInMatrix = listOf(
            0.0f,
            0.45f,
            0.3f,
            0.25f,
            0.3f,
            0.0f,
            0.45f,
            0.25f,
            0.2f,
            0.45f,
            0.0f,
            0.35f,
            0.2f,
            0.4f,
            0.4f,
            0.0f,
          ),
          pullInBarsMin = 2,
          pullInBarsMax = 4,
          barsPerLeadMin = 4,
          barsPerLeadMax = 8,
        ),
        seed = 0,
        bpm = 104.0f,
        envelopeType = EnvelopeType.AD,
        rootNote = RootNote.D,
        scaleType = ScaleType.MINOR,
        genre = GenreProfile(
          swingAmount = 0.05f,
          ghostProbability = 0.15f,
          noteRangeLow = 36,
          noteRangeHigh = 76,
          rhythmDensity = 0.55f,
          progressionStyle = ProgressionStyle.DARK,
          chordsPerBar = 2,
          chordTransitionMatrix = null,
          customProgression = listOf(
            ChordStep(
              degree = 0,
              glideRate = 0.0f,
            ),
            ChordStep(
              degree = 6,
              glideRate = 0.0f,
            ),
            ChordStep(
              degree = 5,
              glideRate = 0.0f,
            ),
            ChordStep(
              degree = 2,
              glideRate = 0.0f,
            ),
          ),
        ),
        energy = 0.6f,
        complexity = 0.55f,
        space = 0.5f,
        mood = 0.35f,
        deep = 0.6f,
        stepCount = 32,
        tension = TensionProfile(
          innerBars = 4,
          outerBars = 16,
          outerDepth = 0.5f,
          volume = 0.25f,
          tonal = TonalTension(
            octaveShift = false,
            keyShift = 0,
            halfLick = HalfLick.OFF,
            chromaticPassing = 0.1f,
          ),
          timing = 0.2f,
          evolution = EvolutionTension(
            timbreLow = 0.3f,
            timbreHigh = 0.55f,
            timbreProbability = 0.55f,
            morphLow = -1.0f,
            morphHigh = -1.0f,
            morphProbability = 0.5f,
            harmonicsLow = -1.0f,
            harmonicsHigh = -1.0f,
            harmonicsProbability = 0.3f,
            attackPoint = 0.5f,
            releaseSpeed = 0.4f,
          ),
          spurtChance = 0.1f,
        ),
        arrangement = Arrangement(
          sections = listOf(
            Section(
              name = "intro",
              barsMin = 2,
              barsMax = 4,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 1,
                  weight = 1.0f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.5f,
                complexity = 0.4f,
                space = 1.3f,
                mood = 0.9f,
              ),
              tensionOverride = null,
              soloMode = SoloMode.LongFill(
                probability = 1.0f,
                barsMin = 2,
                barsMax = 2,
              ),
              trackOverrides = mapOf(
                3 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = null,
                  volume = 0.55f,
                  reverbSend = null,
                  delaySend = 0.7f,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
              ),
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = listOf(
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 6,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 5,
                  glideRate = 0.0f,
                ),
              ),
              chordsPerBar = 2,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "groove",
              barsMin = 4,
              barsMax = 4,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 2,
                  weight = 0.6f,
                  transitionBars = 0,
                ),
                SectionTransition(
                  targetIndex = 3,
                  weight = 0.15f,
                  transitionBars = 0,
                ),
                SectionTransition(
                  targetIndex = 4,
                  weight = 0.25f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 1.05f,
                complexity = 0.9f,
                space = 0.8f,
                mood = 1.0f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = mapOf(
                1 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = 0.65f,
                  volume = 0.85f,
                  reverbSend = null,
                  delaySend = null,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
                2 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = 0.75f,
                  volume = 0.85f,
                  reverbSend = null,
                  delaySend = null,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
                0 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = 0.55f,
                  volume = null,
                  reverbSend = null,
                  delaySend = null,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
              ),
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = null,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "sax_verse",
              barsMin = 4,
              barsMax = 6,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 3,
                  weight = 0.5f,
                  transitionBars = 0,
                ),
                SectionTransition(
                  targetIndex = 1,
                  weight = 0.25f,
                  transitionBars = 0,
                ),
                SectionTransition(
                  targetIndex = 4,
                  weight = 0.25f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 1.0f,
                complexity = 1.1f,
                space = 0.9f,
                mood = 0.85f,
              ),
              tensionOverride = null,
              soloMode = SoloMode.LickBuilder(
                probability = 0.85f,
                mutationRate = 0.3f,
              ),
              trackOverrides = mapOf(
                6 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = 0.55f,
                  volume = 0.85f,
                  reverbSend = null,
                  delaySend = null,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = ChordFollow.FIXED,
                ),
              ),
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = listOf(
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 6,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 5,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 2,
                  glideRate = 0.0f,
                ),
              ),
              chordsPerBar = 2,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "sax_solo",
              barsMin = 4,
              barsMax = 6,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 2,
                  weight = 0.4f,
                  transitionBars = 0,
                ),
                SectionTransition(
                  targetIndex = 4,
                  weight = 0.4f,
                  transitionBars = 0,
                ),
                SectionTransition(
                  targetIndex = 1,
                  weight = 0.2f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.4f,
              macroOverrides = MacroOverrides(
                energy = 1.15f,
                complexity = 1.3f,
                space = 0.9f,
                mood = 0.9f,
              ),
              tensionOverride = null,
              soloMode = SoloMode.Jam(
                probability = 0.85f,
                lickInfluence = 0.5f,
              ),
              trackOverrides = mapOf(
                6 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = 0.65f,
                  volume = 0.95f,
                  reverbSend = null,
                  delaySend = null,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = ChordFollow.FIXED,
                ),
              ),
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = null,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "breakdown",
              barsMin = 4,
              barsMax = 4,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 5,
                  weight = 0.65f,
                  transitionBars = 4,
                ),
                SectionTransition(
                  targetIndex = 1,
                  weight = 0.35f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.45f,
                complexity = 0.5f,
                space = 1.4f,
                mood = 0.8f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = mapOf(
                6 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = 0.25f,
                  volume = 0.4f,
                  reverbSend = null,
                  delaySend = null,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
              ),
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = listOf(
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 6,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 5,
                  glideRate = 0.0f,
                ),
              ),
              chordsPerBar = 2,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "outro",
              barsMin = 4,
              barsMax = 6,
              barStep = 1,
              transitions = emptyList(),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.55f,
                complexity = 0.4f,
                space = 1.8f,
                mood = 0.75f,
              ),
              tensionOverride = null,
              soloMode = SoloMode.LongFill(
                probability = 1.0f,
                barsMin = 2,
                barsMax = 2,
              ),
              trackOverrides = mapOf(
                7 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = null,
                  volume = 0.8f,
                  reverbSend = 0.75f,
                  delaySend = 0.85f,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
                3 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = null,
                  volume = null,
                  reverbSend = null,
                  delaySend = 0.8f,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
                6 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = null,
                  volume = 0.5f,
                  reverbSend = null,
                  delaySend = 0.85f,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
                4 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = null,
                  volume = null,
                  reverbSend = null,
                  delaySend = 0.6f,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
                5 to TrackSectionOverride(
                  holdProbability = null,
                  holdLengthMin = null,
                  holdLengthMax = null,
                  density = null,
                  volume = null,
                  reverbSend = null,
                  delaySend = 0.6f,
                  envelopeProfile = null,
                  compingStyle = null,
                  sectionInversion = null,
                  arpMode = null,
                  chordFollow = null,
                ),
              ),
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = listOf(
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
              ),
              chordsPerBar = 1,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
          ),
          introIndex = 0,
          outroIndex = 5,
          defaultSectionBars = 8,
          lengthSeconds = 150..240,
          transitionOut = null,
        ),
        progressionAnchor = ProgressionAnchor.EVERY_4,
        progressionDriftRange = 0.1f,
        effects = VibeEffects(
          delayTimeA = 0.25f,
          delayTimeB = 0.375f,
          delayFeedback = 0.4f,
          delayDamping = 0.4f,
          reverbSize = 0.5f,
          reverbDamping = 0.5f,
          reverbBrightness = 0.4f,
          deepFloor = 0.35f,
        ),
        lickWah = null,
        anomalies = emptyList(),
      )
      }
}
