package org.balch.orpheus.features.pulsar.vibes

import dev.zacsweers.metro.ContributesIntoSet
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.binding
import kotlin.String
import org.balch.orpheus.core.audio.OrpheusEngineId
import org.balch.orpheus.core.di.FeatureScope
import org.balch.orpheus.features.pulsar.models.Album
import org.balch.orpheus.features.pulsar.models.Arrangement
import org.balch.orpheus.features.pulsar.models.Band
import org.balch.orpheus.features.pulsar.models.BandMember
import org.balch.orpheus.features.pulsar.models.BarStrategy
import org.balch.orpheus.features.pulsar.models.ChordFollow
import org.balch.orpheus.features.pulsar.models.ChordStep
import org.balch.orpheus.features.pulsar.models.EnvelopeProfile
import org.balch.orpheus.features.pulsar.models.EnvelopeType
import org.balch.orpheus.features.pulsar.models.Evolution
import org.balch.orpheus.features.pulsar.models.EvolutionTension
import org.balch.orpheus.features.pulsar.models.GenreProfile
import org.balch.orpheus.features.pulsar.models.Lick
import org.balch.orpheus.features.pulsar.models.LickMode
import org.balch.orpheus.features.pulsar.models.LickStep
import org.balch.orpheus.features.pulsar.models.LpgMode
import org.balch.orpheus.features.pulsar.models.MacroOverrides
import org.balch.orpheus.features.pulsar.models.MacroSource
import org.balch.orpheus.features.pulsar.models.MacroTarget
import org.balch.orpheus.features.pulsar.models.OrpheusEngine
import org.balch.orpheus.features.pulsar.models.PitchEvolution
import org.balch.orpheus.features.pulsar.models.ProgressionAnchor
import org.balch.orpheus.features.pulsar.models.ProgressionStyle
import org.balch.orpheus.features.pulsar.models.RootNote
import org.balch.orpheus.features.pulsar.models.ScaleType
import org.balch.orpheus.features.pulsar.models.Section
import org.balch.orpheus.features.pulsar.models.SectionTransition
import org.balch.orpheus.features.pulsar.models.SoloMode
import org.balch.orpheus.features.pulsar.models.TensionProfile
import org.balch.orpheus.features.pulsar.models.TonalTension
import org.balch.orpheus.features.pulsar.models.TrackMacroMap
import org.balch.orpheus.features.pulsar.models.TrackRole
import org.balch.orpheus.features.pulsar.models.TrackVoice
import org.balch.orpheus.features.pulsar.models.Vibe
import org.balch.orpheus.features.pulsar.models.VibeEffects
import org.balch.orpheus.features.pulsar.models.VibeProvider
import org.balch.orpheus.features.pulsar.models.VoidAnomaly

/**
 * Lost In Space — generated from an AI-archived vibe JSON by tools:vibe-codegen (NOT hand-authored).
 * A compiling, faithful starting point; polish (idiom collapsing, musical notes, tuning)
 * via the vibe-creator skill once this vibe earns a permanent keep.
 */
@Inject
@ContributesIntoSet(FeatureScope::class, binding = binding<VibeProvider>())
public class LostInSpaceVibe : VibeProvider {
  override val name: String = "Lost In Space"

  override val vibe: Vibe by lazy {
    Vibe(
      name = "Lost In Space",
      album = Album.STEALTH,
      tracks = listOf(
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.BD,
            volume = 0.55f,
            harmonics = 0.4f,
            timbre = 0.3f,
            morph = 0.5f,
            modLfoRate = 0.1f,
            modLfoDepth = 0.1f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.2f,
            holdProbability = 0.5f,
            holdLengthMin = 4,
            holdLengthMax = 8,
            delaySend = 0.25f,
            reverbSend = 0.6f,
            noteRangeLow = 36,
            noteRangeHigh = 48,
            reverbBrightness = 0.3f,
            delayFeedback = null,
            glideRate = 0.0f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.BD,
            volume = 0.55f,
            harmonics = 0.4f,
            timbre = 0.3f,
            morph = 0.5f,
            modLfoRate = 0.1f,
            modLfoDepth = 0.1f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.2f,
            holdProbability = 0.5f,
            holdLengthMin = 4,
            holdLengthMax = 8,
            delaySend = 0.25f,
            reverbSend = 0.6f,
            noteRangeLow = 36,
            noteRangeHigh = 48,
            reverbBrightness = 0.3f,
            delayFeedback = null,
            glideRate = 0.0f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.ROOT_ONLY,
            lickMode = LickMode.None,
          ),
          pan = 0.0f,
          density = 0.2f,
          envelopeProfile = EnvelopeProfile.DRONE,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.5f,
              max = 0.8f,
            ),
            energyDensity = MacroTarget(
              min = 0.1f,
              max = 0.4f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.0f,
            ),
            complexityVariation = MacroTarget(
              min = 0.0f,
              max = 0.1f,
            ),
            spaceDecay = MacroTarget(
              min = 0.6f,
              max = 0.9f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.3f,
              max = 0.6f,
            ),
            moodTimbre = MacroTarget(
              min = 0.2f,
              max = 0.5f,
            ),
          ),
          barStrategy = BarStrategy.MUTATE,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = null,
          ),
        ),
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.GRN,
            volume = 0.75f,
            harmonics = 0.6f,
            timbre = 0.7f,
            morph = 0.65f,
            modLfoRate = 0.08f,
            modLfoDepth = 0.3f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.4f,
            holdProbability = 0.6f,
            holdLengthMin = 4,
            holdLengthMax = 10,
            delaySend = 0.5f,
            reverbSend = 0.7f,
            noteRangeLow = 42,
            noteRangeHigh = 66,
            reverbBrightness = 0.5f,
            delayFeedback = null,
            glideRate = 0.3f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.6f,
            lpgColour = 0.4f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.1f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.1f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.GRN,
            volume = 0.75f,
            harmonics = 0.6f,
            timbre = 0.7f,
            morph = 0.65f,
            modLfoRate = 0.08f,
            modLfoDepth = 0.3f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.4f,
            holdProbability = 0.6f,
            holdLengthMin = 4,
            holdLengthMax = 10,
            delaySend = 0.5f,
            reverbSend = 0.7f,
            noteRangeLow = 42,
            noteRangeHigh = 66,
            reverbBrightness = 0.5f,
            delayFeedback = null,
            glideRate = 0.3f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.6f,
            lpgColour = 0.4f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.1f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.1f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.ROOT_ONLY,
            lickMode = LickMode.None,
          ),
          pan = -0.35f,
          density = 0.25f,
          envelopeProfile = EnvelopeProfile.MELODIC,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.5f,
              max = 0.9f,
            ),
            energyDensity = MacroTarget(
              min = 0.2f,
              max = 0.6f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.1f,
            ),
            complexityVariation = MacroTarget(
              min = 0.1f,
              max = 0.4f,
            ),
            spaceDecay = MacroTarget(
              min = 0.4f,
              max = 0.8f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.4f,
              max = 0.8f,
            ),
            moodTimbre = MacroTarget(
              min = 0.5f,
              max = 0.9f,
            ),
          ),
          barStrategy = BarStrategy.MUTATE,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = null,
          ),
        ),
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.PAR,
            volume = 0.72f,
            harmonics = 0.8f,
            timbre = 0.65f,
            morph = 0.9f,
            modLfoRate = 0.04f,
            modLfoDepth = 0.5f,
            modLfoShape = 0.4f,
            modLfoCoupling = 0.3f,
            holdProbability = 0.75f,
            holdLengthMin = 6,
            holdLengthMax = 14,
            delaySend = 0.6f,
            reverbSend = 0.75f,
            noteRangeLow = 60,
            noteRangeHigh = 84,
            reverbBrightness = 0.65f,
            delayFeedback = null,
            glideRate = 0.2f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = true,
            pinTimbre = true,
            pinMorph = true,
            harmonicsModulation = 0.05f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.25f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.PAR,
            volume = 0.72f,
            harmonics = 0.8f,
            timbre = 0.65f,
            morph = 0.9f,
            modLfoRate = 0.04f,
            modLfoDepth = 0.5f,
            modLfoShape = 0.4f,
            modLfoCoupling = 0.3f,
            holdProbability = 0.75f,
            holdLengthMin = 6,
            holdLengthMax = 14,
            delaySend = 0.6f,
            reverbSend = 0.75f,
            noteRangeLow = 60,
            noteRangeHigh = 84,
            reverbBrightness = 0.65f,
            delayFeedback = null,
            glideRate = 0.2f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = true,
            pinTimbre = true,
            pinMorph = true,
            harmonicsModulation = 0.05f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.25f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.FOLLOW,
            lickMode = LickMode.None,
          ),
          pan = 0.35f,
          density = 0.3f,
          envelopeProfile = EnvelopeProfile.DRONE,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.4f,
              max = 0.8f,
            ),
            energyDensity = MacroTarget(
              min = 0.1f,
              max = 0.35f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.1f,
            ),
            complexityVariation = MacroTarget(
              min = 0.05f,
              max = 0.3f,
            ),
            spaceDecay = MacroTarget(
              min = 0.6f,
              max = 0.9f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.5f,
              max = 0.85f,
            ),
            moodTimbre = MacroTarget(
              min = 0.5f,
              max = 0.8f,
            ),
          ),
          barStrategy = BarStrategy.INDEPENDENT,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = null,
          ),
        ),
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.PD,
            volume = 0.68f,
            harmonics = 0.3f,
            timbre = 0.4f,
            morph = 0.35f,
            modLfoRate = 0.15f,
            modLfoDepth = 0.15f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.2f,
            holdProbability = 0.95f,
            holdLengthMin = 16,
            holdLengthMax = 32,
            delaySend = 0.15f,
            reverbSend = 0.4f,
            noteRangeLow = 28,
            noteRangeHigh = 40,
            reverbBrightness = 0.3f,
            delayFeedback = null,
            glideRate = 0.4f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.1f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.PD,
            volume = 0.68f,
            harmonics = 0.3f,
            timbre = 0.4f,
            morph = 0.35f,
            modLfoRate = 0.15f,
            modLfoDepth = 0.15f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.2f,
            holdProbability = 0.95f,
            holdLengthMin = 16,
            holdLengthMax = 32,
            delaySend = 0.15f,
            reverbSend = 0.4f,
            noteRangeLow = 28,
            noteRangeHigh = 40,
            reverbBrightness = 0.3f,
            delayFeedback = null,
            glideRate = 0.4f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.1f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.ROOT_ONLY,
            lickMode = LickMode.None,
          ),
          pan = 0.0f,
          density = 0.08f,
          envelopeProfile = EnvelopeProfile.DRONE,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.5f,
              max = 0.9f,
            ),
            energyDensity = MacroTarget(
              min = 0.05f,
              max = 0.2f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.0f,
            ),
            complexityVariation = MacroTarget(
              min = 0.0f,
              max = 0.2f,
            ),
            spaceDecay = MacroTarget(
              min = 0.3f,
              max = 0.6f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.2f,
              max = 0.5f,
            ),
            moodTimbre = MacroTarget(
              min = 0.3f,
              max = 0.6f,
            ),
          ),
          barStrategy = BarStrategy.REPEAT,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = null,
          ),
        ),
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.ENS,
            volume = 0.7f,
            harmonics = 0.45f,
            timbre = 0.35f,
            morph = 0.3f,
            modLfoRate = 0.02f,
            modLfoDepth = 0.4f,
            modLfoShape = 0.1f,
            modLfoCoupling = 0.3f,
            holdProbability = 0.9f,
            holdLengthMin = 16,
            holdLengthMax = 32,
            delaySend = 0.35f,
            reverbSend = 0.6f,
            noteRangeLow = 48,
            noteRangeHigh = 64,
            reverbBrightness = 0.4f,
            delayFeedback = null,
            glideRate = 0.3f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.ENS,
            volume = 0.7f,
            harmonics = 0.45f,
            timbre = 0.35f,
            morph = 0.3f,
            modLfoRate = 0.02f,
            modLfoDepth = 0.4f,
            modLfoShape = 0.1f,
            modLfoCoupling = 0.3f,
            holdProbability = 0.9f,
            holdLengthMin = 16,
            holdLengthMax = 32,
            delaySend = 0.35f,
            reverbSend = 0.6f,
            noteRangeLow = 48,
            noteRangeHigh = 64,
            reverbBrightness = 0.4f,
            delayFeedback = null,
            glideRate = 0.3f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.ROOT_ONLY,
            lickMode = LickMode.None,
          ),
          pan = -0.2f,
          density = 0.1f,
          envelopeProfile = EnvelopeProfile.DRONE,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.5f,
              max = 0.9f,
            ),
            energyDensity = MacroTarget(
              min = 0.05f,
              max = 0.2f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.0f,
            ),
            complexityVariation = MacroTarget(
              min = 0.0f,
              max = 0.2f,
            ),
            spaceDecay = MacroTarget(
              min = 0.25f,
              max = 0.25f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.4f,
              max = 0.4f,
            ),
            moodTimbre = MacroTarget(
              min = 0.3f,
              max = 0.3f,
            ),
          ),
          barStrategy = BarStrategy.REPEAT,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = null,
          ),
        ),
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.DX2,
            volume = 0.78f,
            harmonics = 0.428f,
            timbre = 0.55f,
            morph = 0.45f,
            modLfoRate = 0.1f,
            modLfoDepth = 0.5f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.5f,
            holdProbability = 0.8f,
            holdLengthMin = 4,
            holdLengthMax = 12,
            delaySend = 0.55f,
            reverbSend = 0.65f,
            noteRangeLow = 54,
            noteRangeHigh = 78,
            reverbBrightness = 0.5f,
            delayFeedback = null,
            glideRate = 0.5f,
            lpgMode = LpgMode.SUSTAINED,
            lpgDecay = 0.8f,
            lpgColour = 0.3f,
            pinHarmonics = true,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.05f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.02f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.DX2,
            volume = 0.78f,
            harmonics = 0.428f,
            timbre = 0.55f,
            morph = 0.45f,
            modLfoRate = 0.1f,
            modLfoDepth = 0.5f,
            modLfoShape = 0.3f,
            modLfoCoupling = 0.5f,
            holdProbability = 0.8f,
            holdLengthMin = 4,
            holdLengthMax = 12,
            delaySend = 0.55f,
            reverbSend = 0.65f,
            noteRangeLow = 54,
            noteRangeHigh = 78,
            reverbBrightness = 0.5f,
            delayFeedback = null,
            glideRate = 0.5f,
            lpgMode = LpgMode.SUSTAINED,
            lpgDecay = 0.8f,
            lpgColour = 0.3f,
            pinHarmonics = true,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.05f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.02f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.FIXED,
            lickMode = LickMode.Fill,
          ),
          pan = 0.1f,
          density = 0.18f,
          envelopeProfile = EnvelopeProfile.DRONE,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.6f,
              max = 1.0f,
            ),
            energyDensity = MacroTarget(
              min = 0.1f,
              max = 0.4f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.1f,
            ),
            complexityVariation = MacroTarget(
              min = 0.1f,
              max = 0.3f,
            ),
            spaceDecay = MacroTarget(
              min = 0.3f,
              max = 0.7f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.4f,
              max = 0.7f,
            ),
            moodTimbre = MacroTarget(
              min = 0.4f,
              max = 0.8f,
            ),
          ),
          barStrategy = BarStrategy.MUTATE,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = PitchEvolution.Contour(
              driftRange = 0.15f,
            ),
          ),
        ),
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.STR,
            volume = 0.55f,
            harmonics = 0.5f,
            timbre = 0.4f,
            morph = 0.25f,
            modLfoRate = 0.03f,
            modLfoDepth = 0.4f,
            modLfoShape = 0.2f,
            modLfoCoupling = 0.3f,
            holdProbability = 0.9f,
            holdLengthMin = 12,
            holdLengthMax = 28,
            delaySend = 0.4f,
            reverbSend = 0.7f,
            noteRangeLow = 43,
            noteRangeHigh = 60,
            reverbBrightness = 0.45f,
            delayFeedback = null,
            glideRate = 0.0f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.STR,
            volume = 0.55f,
            harmonics = 0.5f,
            timbre = 0.4f,
            morph = 0.25f,
            modLfoRate = 0.03f,
            modLfoDepth = 0.4f,
            modLfoShape = 0.2f,
            modLfoCoupling = 0.3f,
            holdProbability = 0.9f,
            holdLengthMin = 12,
            holdLengthMax = 28,
            delaySend = 0.4f,
            reverbSend = 0.7f,
            noteRangeLow = 43,
            noteRangeHigh = 60,
            reverbBrightness = 0.45f,
            delayFeedback = null,
            glideRate = 0.0f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.ROOT_ONLY,
            lickMode = LickMode.None,
          ),
          pan = 0.2f,
          density = 0.1f,
          envelopeProfile = EnvelopeProfile.DRONE,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.5f,
              max = 0.9f,
            ),
            energyDensity = MacroTarget(
              min = 0.05f,
              max = 0.2f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.1f,
            ),
            complexityVariation = MacroTarget(
              min = 0.0f,
              max = 0.2f,
            ),
            spaceDecay = MacroTarget(
              min = 0.2f,
              max = 0.2f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.5f,
              max = 0.5f,
            ),
            moodTimbre = MacroTarget(
              min = 0.4f,
              max = 0.4f,
            ),
          ),
          barStrategy = BarStrategy.INDEPENDENT,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = null,
          ),
        ),
        TrackVoice(
          engineEdm = OrpheusEngine(
            engineId = OrpheusEngineId.SWM,
            volume = 0.5f,
            harmonics = 0.7f,
            timbre = 0.5f,
            morph = 0.8f,
            modLfoRate = 0.06f,
            modLfoDepth = 0.45f,
            modLfoShape = 0.4f,
            modLfoCoupling = 0.4f,
            holdProbability = 0.5f,
            holdLengthMin = 4,
            holdLengthMax = 10,
            delaySend = 0.6f,
            reverbSend = 0.8f,
            noteRangeLow = 50,
            noteRangeHigh = 72,
            reverbBrightness = 0.6f,
            delayFeedback = null,
            glideRate = 0.0f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          engineSpace = OrpheusEngine(
            engineId = OrpheusEngineId.SWM,
            volume = 0.5f,
            harmonics = 0.7f,
            timbre = 0.5f,
            morph = 0.8f,
            modLfoRate = 0.06f,
            modLfoDepth = 0.45f,
            modLfoShape = 0.4f,
            modLfoCoupling = 0.4f,
            holdProbability = 0.5f,
            holdLengthMin = 4,
            holdLengthMax = 10,
            delaySend = 0.6f,
            reverbSend = 0.8f,
            noteRangeLow = 50,
            noteRangeHigh = 72,
            reverbBrightness = 0.6f,
            delayFeedback = null,
            glideRate = 0.0f,
            lpgMode = LpgMode.ENGINE_DEFAULT,
            lpgDecay = 0.5f,
            lpgColour = 0.5f,
            pinHarmonics = false,
            pinTimbre = false,
            pinMorph = false,
            harmonicsModulation = 0.0f,
            harmonicsMacroSource = MacroSource.MOOD,
            harmonicsMacroRange = 0.0f,
          ),
          role = TrackRole.Melodic(
            chordFollow = ChordFollow.FOLLOW,
            lickMode = LickMode.None,
          ),
          pan = -0.4f,
          density = 0.15f,
          envelopeProfile = EnvelopeProfile.WILD,
          macroMap = TrackMacroMap(
            energyVolume = MacroTarget(
              min = 0.2f,
              max = 0.6f,
            ),
            energyDensity = MacroTarget(
              min = 0.1f,
              max = 0.4f,
            ),
            complexitySwing = MacroTarget(
              min = 0.0f,
              max = 0.4f,
            ),
            complexityVariation = MacroTarget(
              min = 0.15f,
              max = 0.6f,
            ),
            spaceDecay = MacroTarget(
              min = 0.4f,
              max = 0.8f,
            ),
            moodHarmonics = MacroTarget(
              min = 0.4f,
              max = 0.8f,
            ),
            moodTimbre = MacroTarget(
              min = 0.3f,
              max = 0.7f,
            ),
          ),
          barStrategy = BarStrategy.INDEPENDENT,
          evolutionWeight = -1.0f,
          soloBehavior = null,
          duckingProfile = null,
          evolution = Evolution(
            rhythmic = null,
            pitch = null,
          ),
        ),
      ),
      lick = Lick(
        steps = listOf(
          LickStep(
            scaleDegree = 0,
            duration = 4.0f,
            velocity = 0.65f,
            glideRate = 0.5f,
          ),
          LickStep(
            scaleDegree = 1,
            duration = 2.0f,
            velocity = 0.6f,
            glideRate = 0.5f,
          ),
          LickStep(
            scaleDegree = 2,
            duration = 2.0f,
            velocity = 0.65f,
            glideRate = 0.5f,
          ),
          LickStep(
            scaleDegree = 4,
            duration = 4.0f,
            velocity = 0.7f,
            glideRate = 0.5f,
          ),
          LickStep(
            scaleDegree = 3,
            duration = 2.0f,
            velocity = 0.6f,
            glideRate = 0.5f,
          ),
          LickStep(
            scaleDegree = 1,
            duration = 2.0f,
            velocity = 0.55f,
            glideRate = 0.5f,
          ),
        ),
        loopLength = 16,
      ),
      lickMutation = 0.25f,
      lickOctave = 4,
      band = Band(
        members = listOf(
          BandMember(
            name = "Rhythm",
            tracks = listOf(
              0,
              1,
              2,
            ),
            alwaysActive = true,
            loudness = 0.5f,
            creativity = 0.4f,
            swing = 0.0f,
            drag = 0.0f,
          ),
          BandMember(
            name = "Bassist",
            tracks = listOf(
              3,
            ),
            alwaysActive = true,
            loudness = 0.6f,
            creativity = 0.3f,
            swing = 0.0f,
            drag = 0.0f,
          ),
          BandMember(
            name = "Keys",
            tracks = listOf(
              4,
              5,
            ),
            alwaysActive = true,
            loudness = 0.5f,
            creativity = 0.5f,
            swing = 0.0f,
            drag = 0.0f,
          ),
          BandMember(
            name = "Textures",
            tracks = listOf(
              6,
              7,
            ),
            alwaysActive = true,
            loudness = 0.55f,
            creativity = 0.6f,
            swing = 0.0f,
            drag = 0.0f,
          ),
        ),
        handoffMatrix = listOf(
          0.0f,
          0.2f,
          0.55f,
          0.25f,
          0.15f,
          0.0f,
          0.55f,
          0.3f,
          0.1f,
          0.1f,
          0.0f,
          0.8f,
          0.1f,
          0.1f,
          0.8f,
          0.0f,
        ),
        pullInMatrix = listOf(
          0.0f,
          0.2f,
          0.5f,
          0.3f,
          0.15f,
          0.0f,
          0.55f,
          0.3f,
          0.1f,
          0.15f,
          0.0f,
          0.75f,
          0.1f,
          0.15f,
          0.75f,
          0.0f,
        ),
        pullInBarsMin = 2,
        pullInBarsMax = 6,
        barsPerLeadMin = 4,
        barsPerLeadMax = 8,
      ),
      seed = 42,
      bpm = 65.0f,
      envelopeType = EnvelopeType.TIDES,
      rootNote = RootNote.C_SHARP,
      scaleType = ScaleType.PHRYGIAN,
      genre = GenreProfile(
        swingAmount = 0.0f,
        ghostProbability = 0.15f,
        noteRangeLow = 36,
        noteRangeHigh = 84,
        rhythmDensity = 0.0f,
        progressionStyle = ProgressionStyle.DRONE,
        chordsPerBar = 1,
        chordTransitionMatrix = null,
        customProgression = listOf(
          ChordStep(
            degree = 0,
            glideRate = 0.4f,
          ),
          ChordStep(
            degree = 0,
            glideRate = 0.4f,
          ),
          ChordStep(
            degree = 1,
            glideRate = 0.5f,
          ),
          ChordStep(
            degree = 0,
            glideRate = 0.4f,
          ),
        ),
      ),
      energy = 0.4f,
      complexity = 0.4f,
      space = 0.85f,
      mood = 0.55f,
      deep = 0.7f,
      stepCount = 32,
      tension = TensionProfile(
        innerBars = 8,
        outerBars = 32,
        outerDepth = 0.6f,
        volume = 0.4f,
        tonal = TonalTension(
          octaveShift = false,
          keyShift = 0,
          halfLick = false,
          chromaticPassing = 0.0f,
        ),
        timing = 0.02f,
        evolution = EvolutionTension(
          timbreLow = 0.15f,
          timbreHigh = 0.45f,
          timbreProbability = 0.5f,
          morphLow = 0.1f,
          morphHigh = 0.5f,
          morphProbability = 0.4f,
          harmonicsLow = 0.15f,
          harmonicsHigh = 0.45f,
          harmonicsProbability = 0.3f,
          attackPoint = 0.25f,
          releaseSpeed = 0.8f,
        ),
        spurtChance = 0.0f,
      ),
      arrangement = Arrangement(
        sections = listOf(
          Section(
            name = "initiation",
            barsMin = 6,
            barsMax = 10,
            barStep = 1,
            transitions = listOf(
              SectionTransition(
                targetIndex = 1,
                weight = 1.0f,
                transitionBars = 0,
              ),
            ),
            recencyDecay = 0.4f,
            macroOverrides = MacroOverrides(
              energy = 0.4f,
              complexity = 0.3f,
              space = 1.2f,
              mood = 0.7f,
            ),
            tensionOverride = null,
            soloMode = null,
            trackOverrides = null,
            compingStyle = null,
            compingInversion = null,
            compingHumanization = null,
            chordFollow = null,
            customProgression = null,
            chordsPerBar = null,
            bpmMultiplier = 1.0f,
            exitScratchMs = 0,
            bpmRampBars = 0,
          ),
          Section(
            name = "mirage",
            barsMin = 12,
            barsMax = 20,
            barStep = 1,
            transitions = listOf(
              SectionTransition(
                targetIndex = 2,
                weight = 0.7f,
                transitionBars = 0,
              ),
              SectionTransition(
                targetIndex = 0,
                weight = 0.3f,
                transitionBars = 0,
              ),
            ),
            recencyDecay = 0.5f,
            macroOverrides = MacroOverrides(
              energy = 0.6f,
              complexity = 0.5f,
              space = 1.0f,
              mood = 0.8f,
            ),
            tensionOverride = null,
            soloMode = SoloMode.LickBuilder(
              probability = 0.6f,
              mutationRate = 0.3f,
            ),
            trackOverrides = null,
            compingStyle = null,
            compingInversion = null,
            compingHumanization = null,
            chordFollow = null,
            customProgression = null,
            chordsPerBar = null,
            bpmMultiplier = 1.0f,
            exitScratchMs = 0,
            bpmRampBars = 0,
          ),
          Section(
            name = "dissolve",
            barsMin = 8,
            barsMax = 14,
            barStep = 1,
            transitions = listOf(
              SectionTransition(
                targetIndex = 1,
                weight = 1.0f,
                transitionBars = 0,
              ),
            ),
            recencyDecay = 0.5f,
            macroOverrides = MacroOverrides(
              energy = 0.3f,
              complexity = 0.7f,
              space = 1.4f,
              mood = 1.1f,
            ),
            tensionOverride = null,
            soloMode = null,
            trackOverrides = null,
            compingStyle = null,
            compingInversion = null,
            compingHumanization = null,
            chordFollow = null,
            customProgression = null,
            chordsPerBar = null,
            bpmMultiplier = 1.0f,
            exitScratchMs = 0,
            bpmRampBars = 0,
          ),
        ),
        introIndex = 0,
        outroIndex = 2,
        defaultSectionBars = 8,
        lengthSeconds = 180..300,
        transitionOut = null,
      ),
      progressionAnchor = ProgressionAnchor.EVERY_8,
      progressionDriftRange = 0.1f,
      effects = VibeEffects(
        delayTimeA = 0.5f,
        delayTimeB = 0.75f,
        delayFeedback = 0.65f,
        delayDamping = 0.45f,
        reverbSize = 0.9f,
        reverbDamping = 0.4f,
        reverbBrightness = 0.4f,
        deepFloor = 0.45f,
      ),
      anomalies = listOf(
        VoidAnomaly(
          probability = 0.015f,  // ship value — rare (~1 void every couple of songs); the manual anomaly trigger can summon one on demand
          floorLevel = 0.3f,
          rampDownBars = 2.0f,
          floorBarsMin = 1.0f,
          floorBarsMax = 2.0f,
          rampUpBars = 1f,
          ghostIntensity = 0.4f,
        ),
      ),
    )
  }
}
