package org.balch.orpheus.features.pulsar.vibes

import dev.zacsweers.metro.ContributesIntoSet
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.binding
import kotlin.String
import org.balch.orpheus.core.audio.OrpheusEngineId
import org.balch.orpheus.core.di.FeatureScope
import org.balch.orpheus.features.pulsar.anonmalies.WahAnomaly
import org.balch.orpheus.features.pulsar.models.Album
import org.balch.orpheus.features.pulsar.models.ArpDirection
import org.balch.orpheus.features.pulsar.models.ArpMode
import org.balch.orpheus.features.pulsar.models.Arrangement
import org.balch.orpheus.features.pulsar.models.BarStrategy
import org.balch.orpheus.features.pulsar.models.ChordComping
import org.balch.orpheus.features.pulsar.models.ChordFollow
import org.balch.orpheus.features.pulsar.models.ChordStep
import org.balch.orpheus.features.pulsar.models.CompingFills
import org.balch.orpheus.features.pulsar.models.CompingHumanization
import org.balch.orpheus.features.pulsar.models.CompingStyle
import org.balch.orpheus.features.pulsar.models.EnvelopeProfile
import org.balch.orpheus.features.pulsar.models.EnvelopeType
import org.balch.orpheus.features.pulsar.models.Evolution
import org.balch.orpheus.features.pulsar.models.EvolutionTension
import org.balch.orpheus.features.pulsar.models.FillType
import org.balch.orpheus.features.pulsar.models.GenreProfile
import org.balch.orpheus.features.pulsar.models.HalfLick
import org.balch.orpheus.features.pulsar.models.Lick
import org.balch.orpheus.features.pulsar.models.LickMode
import org.balch.orpheus.features.pulsar.models.LickSource
import org.balch.orpheus.features.pulsar.models.LickStep
import org.balch.orpheus.features.pulsar.models.LpgMode
import org.balch.orpheus.features.pulsar.models.MacroOverrides
import org.balch.orpheus.features.pulsar.models.MacroSource
import org.balch.orpheus.features.pulsar.models.MacroTarget
import org.balch.orpheus.features.pulsar.models.OrpheusEngine
import org.balch.orpheus.features.pulsar.models.ProgressionAnchor
import org.balch.orpheus.features.pulsar.models.ProgressionStyle
import org.balch.orpheus.features.pulsar.models.RootNote
import org.balch.orpheus.features.pulsar.models.ScaleType
import org.balch.orpheus.features.pulsar.models.Section
import org.balch.orpheus.features.pulsar.models.SectionInversion
import org.balch.orpheus.features.pulsar.models.SectionTransition
import org.balch.orpheus.features.pulsar.models.SoloMode
import org.balch.orpheus.features.pulsar.models.TensionProfile
import org.balch.orpheus.features.pulsar.models.TonalTension
import org.balch.orpheus.features.pulsar.models.TrackMacroMap
import org.balch.orpheus.features.pulsar.models.TrackRole
import org.balch.orpheus.features.pulsar.models.TrackVoice
import org.balch.orpheus.features.pulsar.models.Vibe
import org.balch.orpheus.features.pulsar.models.VibeEffects
import org.balch.orpheus.features.pulsar.models.VibeProvider
import org.balch.orpheus.features.pulsar.models.WahParams

/**
 * Mellow Haze — generated from an AI-archived vibe JSON by tools:vibe-codegen (NOT hand-authored).
 * A compiling, faithful starting point; polish (idiom collapsing, musical notes, tuning)
 * via the vibe-creator skill once this vibe earns a permanent keep.
 */
@Inject
@ContributesIntoSet(FeatureScope::class, binding = binding<VibeProvider>())
public class MellowHazeVibe : VibeProvider {
  override val name: String = "Mellow Haze"

  override val vibe: Vibe by lazy {
      Vibe(
        name = "Mellow Haze",
        album = Album.RIF,
        tracks = listOf(
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.BD,
              volume = 0.75f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.BD,
              volume = 0.75f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Percussive,
            pan = 0.0f,
            density = 0.35f,
            envelopeProfile = EnvelopeProfile.RHYTHM,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.7f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.SD,
              volume = 0.6f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.2f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.SD,
              volume = 0.6f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.2f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Percussive,
            pan = -0.08f,
            density = 0.25f,
            envelopeProfile = EnvelopeProfile.RHYTHM,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.7f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
            ),
            barStrategy = BarStrategy.FILL,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.HH,
              volume = 0.45f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.HH,
              volume = 0.45f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.0f,
              noteRangeLow = 0,
              noteRangeHigh = 0,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Percussive,
            pan = 0.15f,
            density = 0.5f,
            envelopeProfile = EnvelopeProfile.RHYTHM,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.7f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.VA,
              volume = 0.85f,
              harmonics = 0.2f,
              timbre = 0.3f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.06f,
              noteRangeLow = 26,
              noteRangeHigh = 50,
              reverbBrightness = 0.3f,
              delayFeedback = null,
              glideRate = 0.1f,
              lpgMode = LpgMode.PLUCK,
              lpgDecay = 0.52f,
              lpgColour = 0.45f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.VA,
              volume = 0.85f,
              harmonics = 0.2f,
              timbre = 0.3f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.16f,
              noteRangeLow = 26,
              noteRangeHigh = 50,
              reverbBrightness = 0.3f,
              delayFeedback = null,
              glideRate = 0.1f,
              lpgMode = LpgMode.SUSTAINED,
              lpgDecay = 0.52f,
              lpgColour = 0.45f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.ROOT_ONLY,
              lickMode = LickMode.Fill,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.0f,
            density = 0.7f,
            envelopeProfile = EnvelopeProfile.MELODIC,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.9f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.3f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.ENS,
              volume = 0.45f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.1f,
              reverbSend = 0.3f,
              noteRangeLow = 55,
              noteRangeHigh = 76,
              reverbBrightness = 0.4f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.PLUCK,
              lpgDecay = 0.6f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.ENS,
              volume = 0.45f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.1f,
              reverbSend = 0.4f,
              noteRangeLow = 55,
              noteRangeHigh = 76,
              reverbBrightness = 0.4f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.SUSTAINED,
              lpgDecay = 0.6f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Chordal(
              comping = ChordComping(
                style = CompingStyle.PAD,
                arpMode = ArpMode.AUTO,
                arpSpeed = 0.15f,
                arpDirection = ArpDirection.UP,
                sectionInversion = SectionInversion.FIRST_INVERSION,
                humanization = CompingHumanization(
                  dropProbability = 0.1f,
                  ghostProbability = 0.1f,
                  octaveJumpProbability = 0.0f,
                  extensionProbability = 0.1f,
                ),
                fills = CompingFills(
                  everyNBars = 8,
                  fillType = FillType.TURNAROUND,
                  skipProbability = 0.25f,
                ),
              ),
              chordFollow = ChordFollow.FOLLOW,
            ),
            pan = 0.24f,
            density = 0.5f,
            envelopeProfile = EnvelopeProfile.MELODIC,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.9f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.3f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.WSH,
              volume = 0.45f,
              harmonics = 0.7f,
              timbre = 0.8f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.4f,
              reverbSend = 0.4f,
              noteRangeLow = 57,
              noteRangeHigh = 79,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.35f,
              lpgMode = LpgMode.PLUCK,
              lpgDecay = 0.55f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.WSH,
              volume = 0.45f,
              harmonics = 0.7f,
              timbre = 0.8f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.4f,
              reverbSend = 0.5f,
              noteRangeLow = 57,
              noteRangeHigh = 79,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.35f,
              lpgMode = LpgMode.SUSTAINED,
              lpgDecay = 0.55f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.FOLLOW,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = -0.2f,
            density = 0.2f,
            envelopeProfile = EnvelopeProfile.MELODIC,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.9f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.3f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.CALL_RESPONSE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.STR,
              volume = 0.36f,
              harmonics = 0.4f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.72f,
              holdLengthMin = 2,
              holdLengthMax = 6,
              delaySend = 0.1f,
              reverbSend = 0.3f,
              noteRangeLow = 48,
              noteRangeHigh = 69,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.STR,
              volume = 0.36f,
              harmonics = 0.4f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.72f,
              holdLengthMin = 2,
              holdLengthMax = 6,
              delaySend = 0.1f,
              reverbSend = 0.4f,
              noteRangeLow = 48,
              noteRangeHigh = 69,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Chordal(
              comping = ChordComping(
                style = CompingStyle.PAD,
                arpMode = ArpMode.NEVER,
                arpSpeed = 0.2f,
                arpDirection = ArpDirection.UP,
                sectionInversion = SectionInversion.ROOT_POSITION,
                humanization = CompingHumanization(
                  dropProbability = 0.1f,
                  ghostProbability = 0.05f,
                  octaveJumpProbability = 0.05f,
                  extensionProbability = 0.1f,
                ),
                fills = CompingFills(
                  everyNBars = 0,
                  fillType = FillType.ASCENDING_ARP,
                  skipProbability = 0.0f,
                ),
              ),
              chordFollow = ChordFollow.FOLLOW,
            ),
            pan = -0.24f,
            density = 0.3f,
            envelopeProfile = EnvelopeProfile.EFFECT,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 1.0f,
              ),
              energyDensity = MacroTarget(
                min = 0.4f,
                max = 0.9f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.15f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.3f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.PAR,
              volume = 0.3f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.22f,
              noteRangeLow = 60,
              noteRangeHigh = 76,
              reverbBrightness = 0.62f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.PAR,
              volume = 0.3f,
              harmonics = 0.5f,
              timbre = 0.5f,
              morph = 0.5f,
              modLfoRate = 0.2f,
              modLfoDepth = 0.0f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.0f,
              holdLengthMin = 2,
              holdLengthMax = 8,
              delaySend = 0.0f,
              reverbSend = 0.32f,
              noteRangeLow = 60,
              noteRangeHigh = 76,
              reverbBrightness = 0.62f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Percussive,
            pan = -0.3f,
            density = 0.25f,
            envelopeProfile = EnvelopeProfile.EFFECT,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              energyDensity = MacroTarget(
                min = 0.05f,
                max = 0.25f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.2f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.25f,
              ),
              spaceDecay = MacroTarget(
                min = 0.5f,
                max = 0.9f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
        ),
        lick = Lick(
          steps = listOf(
            LickStep(
              scaleDegree = 0,
              duration = 0.5f,
              velocity = 0.98f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = -1,
              duration = 0.25f,
              velocity = 0.0f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 6,
              duration = 0.75f,
              velocity = 0.9f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 0.5f,
              velocity = 0.86f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = -1,
              duration = 0.25f,
              velocity = 0.0f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 0,
              duration = 1.0f,
              velocity = 1.0f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 5,
              duration = 0.5f,
              velocity = 0.8f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = -1,
              duration = 0.25f,
              velocity = 0.0f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 7,
              duration = 0.5f,
              velocity = 0.92f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = -1,
              duration = 0.25f,
              velocity = 0.0f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 6,
              duration = 0.5f,
              velocity = 0.84f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 0.75f,
              velocity = 0.88f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = -1,
              duration = 0.5f,
              velocity = 0.0f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 3,
              duration = 0.5f,
              velocity = 0.78f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 2,
              duration = 0.5f,
              velocity = 0.74f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = 1,
              duration = 0.25f,
              velocity = 0.7f,
              glideRate = -1.0f,
            ),
            LickStep(
              scaleDegree = -1,
              duration = 0.25f,
              velocity = 0.0f,
              glideRate = -1.0f,
            ),
          ),
          loopLength = 8,
        ),
        lickMutation = 0.22f,
        lickOctave = -1,
        lickRotation = null,
        bassLine = null,
        bassLineMutation = 0.5f,
        bassLineOctave = -1,
        band = null,
        seed = 0,
        bpm = 76.0f,
        envelopeType = EnvelopeType.BLEND,
        rootNote = RootNote.G,
        scaleType = ScaleType.MIXOLYDIAN,
        genre = GenreProfile(
          swingAmount = 0.15f,
          ghostProbability = 0.35f,
          noteRangeLow = 36,
          noteRangeHigh = 64,
          rhythmDensity = 0.4f,
          progressionStyle = ProgressionStyle.POP,
          chordsPerBar = 1,
          chordTransitionMatrix = null,
          customProgression = listOf(
            ChordStep(
              degree = 0,
              glideRate = 0.0f,
            ),
            ChordStep(
              degree = 6,
              glideRate = 0.0f,
            ),
            ChordStep(
              degree = 0,
              glideRate = 0.0f,
            ),
            ChordStep(
              degree = 3,
              glideRate = 0.0f,
            ),
          ),
        ),
        energy = 0.5f,
        complexity = 0.7f,
        space = 0.5f,
        mood = 0.7f,
        deep = 0.4f,
        stepCount = 32,
        tension = TensionProfile(
          innerBars = 8,
          outerBars = 32,
          outerDepth = 0.5f,
          volume = 0.28f,
          tonal = TonalTension(
            octaveShift = true,
            keyShift = 0,
            halfLick = HalfLick.OFF,
            chromaticPassing = 0.12f,
          ),
          timing = 0.18f,
          evolution = EvolutionTension(
            timbreLow = 0.3f,
            timbreHigh = 0.55f,
            timbreProbability = 0.6f,
            morphLow = 0.35f,
            morphHigh = 0.52f,
            morphProbability = 0.5f,
            harmonicsLow = -1.0f,
            harmonicsHigh = -1.0f,
            harmonicsProbability = 0.3f,
            attackPoint = 0.6f,
            releaseSpeed = 0.4f,
          ),
          spurtChance = 0.08f,
        ),
        arrangement = Arrangement(
          sections = listOf(
            Section(
              name = "intro",
              barsMin = 2,
              barsMax = 2,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 1,
                  weight = 1.0f,
                  transitionBars = 2,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.7f,
                complexity = 0.5f,
                space = 0.9f,
                mood = 0.95f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = 1,
              bpmMultiplier = 0.85f,
              bpmRampBars = 1,
              jamCarry = false,
            ),
            Section(
              name = "verse",
              barsMin = 8,
              barsMax = 12,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 2,
                  weight = 0.6f,
                  transitionBars = 2,
                ),
                SectionTransition(
                  targetIndex = 3,
                  weight = 0.25f,
                  transitionBars = 2,
                ),
                SectionTransition(
                  targetIndex = 4,
                  weight = 0.15f,
                  transitionBars = 2,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = null,
              tensionOverride = null,
              soloMode = null,
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = null,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "chorus",
              barsMin = 4,
              barsMax = 8,
              barStep = 4,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 1,
                  weight = 0.45f,
                  transitionBars = 2,
                ),
                SectionTransition(
                  targetIndex = 3,
                  weight = 0.3f,
                  transitionBars = 2,
                ),
                SectionTransition(
                  targetIndex = 4,
                  weight = 0.25f,
                  transitionBars = 2,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 1.1f,
                complexity = 1.15f,
                space = 0.85f,
                mood = 1.2f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = listOf(
                ChordStep(
                  degree = 3,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 4,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
              ),
              chordsPerBar = 1,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "jam",
              barsMin = 8,
              barsMax = 16,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 2,
                  weight = 0.45f,
                  transitionBars = 2,
                ),
                SectionTransition(
                  targetIndex = 1,
                  weight = 0.35f,
                  transitionBars = 2,
                ),
                SectionTransition(
                  targetIndex = 4,
                  weight = 0.2f,
                  transitionBars = 2,
                ),
              ),
              recencyDecay = 0.4f,
              macroOverrides = MacroOverrides(
                energy = 0.95f,
                complexity = 1.35f,
                space = 1.55f,
                mood = 1.1f,
              ),
              tensionOverride = null,
              soloMode = SoloMode.Jam(
                probability = 0.8f,
                lickInfluence = 0.8f,
              ),
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = listOf(
                ChordStep(
                  degree = 6,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 6,
                  glideRate = 0.0f,
                ),
                ChordStep(
                  degree = 0,
                  glideRate = 0.0f,
                ),
              ),
              chordsPerBar = 1,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "breakdown",
              barsMin = 4,
              barsMax = 4,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 2,
                  weight = 0.7f,
                  transitionBars = 4,
                ),
                SectionTransition(
                  targetIndex = 1,
                  weight = 0.3f,
                  transitionBars = 2,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.45f,
                complexity = 0.6f,
                space = 1.4f,
                mood = 0.9f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = 1,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "outro",
              barsMin = 4,
              barsMax = 8,
              barStep = 4,
              transitions = emptyList(),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.9f,
                complexity = 0.9f,
                space = 0.8f,
                mood = 1.15f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = 1,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
          ),
          introIndex = 0,
          outroIndex = 5,
          defaultSectionBars = 8,
          lengthSeconds = 150..240,
          transitionOut = null,
        ),
        progressionAnchor = ProgressionAnchor.EVERY_8,
        progressionDriftRange = 0.1f,
        effects = VibeEffects(
          delayTimeA = 0.33f,
          delayTimeB = 0.5f,
          delayFeedback = 0.4f,
          delayDamping = 0.6f,
          reverbSize = 0.7f,
          reverbDamping = 0.5f,
          reverbBrightness = 0.4f,
          deepFloor = 0.4f,
        ),
        lickWah = null,
        anomalies = listOf(
          WahAnomaly(
            probability = 0.05f,
            durationBarsMin = 4.0f,
            durationBarsMax = 8.0f,
            voice = WahParams(
              rateDivision = 4.0f,
              depth = 0.8f,
              resonanceQ = 4.0f,
              centerHz = 600.0f,
              sweepOctaves = 2.0f,
              wet = 0.7f,
            ),
          ),
        ),
      )
      }
}
