package org.balch.orpheus.features.pulsar.vibes

import dev.zacsweers.metro.ContributesIntoSet
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.binding
import kotlin.String
import org.balch.orpheus.core.audio.OrpheusEngineId
import org.balch.orpheus.core.di.FeatureScope
import org.balch.orpheus.features.pulsar.anonmalies.VoidAnomaly
import org.balch.orpheus.features.pulsar.models.Album
import org.balch.orpheus.features.pulsar.models.Arrangement
import org.balch.orpheus.features.pulsar.models.Band
import org.balch.orpheus.features.pulsar.models.BandMember
import org.balch.orpheus.features.pulsar.models.BarStrategy
import org.balch.orpheus.features.pulsar.models.ChordFollow
import org.balch.orpheus.features.pulsar.models.ChordStep
import org.balch.orpheus.features.pulsar.models.EnvelopeProfile
import org.balch.orpheus.features.pulsar.models.EnvelopeType
import org.balch.orpheus.features.pulsar.models.Evolution
import org.balch.orpheus.features.pulsar.models.EvolutionTension
import org.balch.orpheus.features.pulsar.models.GenreProfile
import org.balch.orpheus.features.pulsar.models.HalfLick
import org.balch.orpheus.features.pulsar.models.Lick
import org.balch.orpheus.features.pulsar.models.LickMode
import org.balch.orpheus.features.pulsar.models.LickSource
import org.balch.orpheus.features.pulsar.models.LickStep
import org.balch.orpheus.features.pulsar.models.LpgMode
import org.balch.orpheus.features.pulsar.models.MacroOverrides
import org.balch.orpheus.features.pulsar.models.MacroSource
import org.balch.orpheus.features.pulsar.models.MacroTarget
import org.balch.orpheus.features.pulsar.models.OrpheusEngine
import org.balch.orpheus.features.pulsar.models.PitchEvolution
import org.balch.orpheus.features.pulsar.models.ProgressionAnchor
import org.balch.orpheus.features.pulsar.models.ProgressionStyle
import org.balch.orpheus.features.pulsar.models.RootNote
import org.balch.orpheus.features.pulsar.models.ScaleType
import org.balch.orpheus.features.pulsar.models.Section
import org.balch.orpheus.features.pulsar.models.SectionTransition
import org.balch.orpheus.features.pulsar.models.SoloMode
import org.balch.orpheus.features.pulsar.models.TensionProfile
import org.balch.orpheus.features.pulsar.models.TonalTension
import org.balch.orpheus.features.pulsar.models.TrackMacroMap
import org.balch.orpheus.features.pulsar.models.TrackRole
import org.balch.orpheus.features.pulsar.models.TrackVoice
import org.balch.orpheus.features.pulsar.models.Vibe
import org.balch.orpheus.features.pulsar.models.VibeEffects
import org.balch.orpheus.features.pulsar.models.VibeProvider

/**
 * Natalis Shimmer — generated from an AI-archived vibe JSON by tools:vibe-codegen (NOT hand-authored).
 * A compiling, faithful starting point; polish (idiom collapsing, musical notes, tuning)
 * via the vibe-creator skill once this vibe earns a permanent keep.
 */
@Inject
@ContributesIntoSet(FeatureScope::class, binding = binding<VibeProvider>())
public class NatalisShimmerVibe : VibeProvider {
  override val name: String = "Natalis Shimmer"

  override val vibe: Vibe by lazy {
      Vibe(
        name = "Natalis Shimmer",
        album = Album.STEALTH,
        tracks = listOf(
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.BD,
              volume = 0.25f,
              harmonics = 0.3f,
              timbre = 0.2f,
              morph = 0.4f,
              modLfoRate = 0.05f,
              modLfoDepth = 0.1f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.8f,
              holdLengthMin = 8,
              holdLengthMax = 16,
              delaySend = 0.1f,
              reverbSend = 0.5f,
              noteRangeLow = 36,
              noteRangeHigh = 48,
              reverbBrightness = 0.2f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.8f,
              lpgColour = 0.3f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.BD,
              volume = 0.25f,
              harmonics = 0.3f,
              timbre = 0.2f,
              morph = 0.4f,
              modLfoRate = 0.05f,
              modLfoDepth = 0.1f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.8f,
              holdLengthMin = 8,
              holdLengthMax = 16,
              delaySend = 0.1f,
              reverbSend = 0.5f,
              noteRangeLow = 36,
              noteRangeHigh = 48,
              reverbBrightness = 0.2f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.8f,
              lpgColour = 0.3f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.ROOT_ONLY,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.0f,
            density = 0.15f,
            envelopeProfile = EnvelopeProfile.DRONE,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              energyDensity = MacroTarget(
                min = 0.05f,
                max = 0.2f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.0f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              spaceDecay = MacroTarget(
                min = 0.6f,
                max = 0.9f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.2f,
                max = 0.5f,
              ),
              moodTimbre = MacroTarget(
                min = 0.2f,
                max = 0.4f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.GRN,
              volume = 0.72f,
              harmonics = 0.5f,
              timbre = 0.6f,
              morph = 0.7f,
              modLfoRate = 0.05f,
              modLfoDepth = 0.35f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.4f,
              holdProbability = 0.8f,
              holdLengthMin = 8,
              holdLengthMax = 16,
              delaySend = 0.5f,
              reverbSend = 0.75f,
              noteRangeLow = 48,
              noteRangeHigh = 72,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.3f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.6f,
              lpgColour = 0.4f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.08f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.15f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.GRN,
              volume = 0.72f,
              harmonics = 0.5f,
              timbre = 0.6f,
              morph = 0.7f,
              modLfoRate = 0.05f,
              modLfoDepth = 0.35f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.4f,
              holdProbability = 0.8f,
              holdLengthMin = 8,
              holdLengthMax = 16,
              delaySend = 0.5f,
              reverbSend = 0.75f,
              noteRangeLow = 48,
              noteRangeHigh = 72,
              reverbBrightness = 0.5f,
              delayFeedback = null,
              glideRate = 0.3f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.6f,
              lpgColour = 0.4f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.08f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.15f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.ROOT_ONLY,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = -0.35f,
            density = 0.2f,
            envelopeProfile = EnvelopeProfile.DRONE,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 0.8f,
              ),
              energyDensity = MacroTarget(
                min = 0.15f,
                max = 0.4f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              complexityVariation = MacroTarget(
                min = 0.05f,
                max = 0.25f,
              ),
              spaceDecay = MacroTarget(
                min = 0.5f,
                max = 0.9f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.35f,
                max = 0.7f,
              ),
              moodTimbre = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.PAR,
              volume = 0.68f,
              harmonics = 0.75f,
              timbre = 0.55f,
              morph = 0.8f,
              modLfoRate = 0.03f,
              modLfoDepth = 0.4f,
              modLfoShape = 0.4f,
              modLfoCoupling = 0.3f,
              holdProbability = 0.85f,
              holdLengthMin = 12,
              holdLengthMax = 24,
              delaySend = 0.55f,
              reverbSend = 0.8f,
              noteRangeLow = 60,
              noteRangeHigh = 84,
              reverbBrightness = 0.6f,
              delayFeedback = null,
              glideRate = 0.2f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = true,
              pinTimbre = true,
              pinMorph = true,
              harmonicsModulation = 0.05f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.2f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.PAR,
              volume = 0.68f,
              harmonics = 0.75f,
              timbre = 0.55f,
              morph = 0.8f,
              modLfoRate = 0.03f,
              modLfoDepth = 0.4f,
              modLfoShape = 0.4f,
              modLfoCoupling = 0.3f,
              holdProbability = 0.85f,
              holdLengthMin = 12,
              holdLengthMax = 24,
              delaySend = 0.55f,
              reverbSend = 0.8f,
              noteRangeLow = 60,
              noteRangeHigh = 84,
              reverbBrightness = 0.6f,
              delayFeedback = null,
              glideRate = 0.2f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = true,
              pinTimbre = true,
              pinMorph = true,
              harmonicsModulation = 0.05f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.2f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.FOLLOW,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.35f,
            density = 0.25f,
            envelopeProfile = EnvelopeProfile.DRONE,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.4f,
                max = 0.75f,
              ),
              energyDensity = MacroTarget(
                min = 0.1f,
                max = 0.3f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.0f,
              ),
              complexityVariation = MacroTarget(
                min = 0.05f,
                max = 0.2f,
              ),
              spaceDecay = MacroTarget(
                min = 0.6f,
                max = 0.9f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.5f,
                max = 0.8f,
              ),
              moodTimbre = MacroTarget(
                min = 0.45f,
                max = 0.75f,
              ),
            ),
            barStrategy = BarStrategy.INDEPENDENT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.PD,
              volume = 0.75f,
              harmonics = 0.25f,
              timbre = 0.35f,
              morph = 0.3f,
              modLfoRate = 0.08f,
              modLfoDepth = 0.2f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.98f,
              holdLengthMin = 16,
              holdLengthMax = 32,
              delaySend = 0.2f,
              reverbSend = 0.5f,
              noteRangeLow = 28,
              noteRangeHigh = 40,
              reverbBrightness = 0.25f,
              delayFeedback = null,
              glideRate = 0.5f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.08f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.PD,
              volume = 0.75f,
              harmonics = 0.25f,
              timbre = 0.35f,
              morph = 0.3f,
              modLfoRate = 0.08f,
              modLfoDepth = 0.2f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.2f,
              holdProbability = 0.98f,
              holdLengthMin = 16,
              holdLengthMax = 32,
              delaySend = 0.2f,
              reverbSend = 0.5f,
              noteRangeLow = 28,
              noteRangeHigh = 40,
              reverbBrightness = 0.25f,
              delayFeedback = null,
              glideRate = 0.5f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.08f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.ROOT_ONLY,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.0f,
            density = 0.05f,
            envelopeProfile = EnvelopeProfile.DRONE,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.6f,
                max = 0.95f,
              ),
              energyDensity = MacroTarget(
                min = 0.05f,
                max = 0.15f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.0f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              spaceDecay = MacroTarget(
                min = 0.4f,
                max = 0.7f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.2f,
                max = 0.45f,
              ),
              moodTimbre = MacroTarget(
                min = 0.3f,
                max = 0.55f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.ENS,
              volume = 0.75f,
              harmonics = 0.4f,
              timbre = 0.3f,
              morph = 0.25f,
              modLfoRate = 0.02f,
              modLfoDepth = 0.35f,
              modLfoShape = 0.1f,
              modLfoCoupling = 0.3f,
              holdProbability = 0.95f,
              holdLengthMin = 16,
              holdLengthMax = 32,
              delaySend = 0.3f,
              reverbSend = 0.7f,
              noteRangeLow = 48,
              noteRangeHigh = 64,
              reverbBrightness = 0.35f,
              delayFeedback = null,
              glideRate = 0.4f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.ENS,
              volume = 0.75f,
              harmonics = 0.4f,
              timbre = 0.3f,
              morph = 0.25f,
              modLfoRate = 0.02f,
              modLfoDepth = 0.35f,
              modLfoShape = 0.1f,
              modLfoCoupling = 0.3f,
              holdProbability = 0.95f,
              holdLengthMin = 16,
              holdLengthMax = 32,
              delaySend = 0.3f,
              reverbSend = 0.7f,
              noteRangeLow = 48,
              noteRangeHigh = 64,
              reverbBrightness = 0.35f,
              delayFeedback = null,
              glideRate = 0.4f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.ROOT_ONLY,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = -0.2f,
            density = 0.08f,
            envelopeProfile = EnvelopeProfile.DRONE,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.6f,
                max = 0.9f,
              ),
              energyDensity = MacroTarget(
                min = 0.05f,
                max = 0.15f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.0f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              spaceDecay = MacroTarget(
                min = 0.25f,
                max = 0.25f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.35f,
                max = 0.35f,
              ),
              moodTimbre = MacroTarget(
                min = 0.25f,
                max = 0.25f,
              ),
            ),
            barStrategy = BarStrategy.REPEAT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.DX2,
              volume = 0.82f,
              harmonics = 0.35f,
              timbre = 0.5f,
              morph = 0.4f,
              modLfoRate = 0.08f,
              modLfoDepth = 0.4f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.5f,
              holdProbability = 0.85f,
              holdLengthMin = 4,
              holdLengthMax = 12,
              delaySend = 0.7f,
              reverbSend = 0.8f,
              noteRangeLow = 54,
              noteRangeHigh = 78,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.6f,
              lpgMode = LpgMode.SUSTAINED,
              lpgDecay = 0.8f,
              lpgColour = 0.3f,
              pinHarmonics = true,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.05f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.02f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.DX2,
              volume = 0.82f,
              harmonics = 0.35f,
              timbre = 0.5f,
              morph = 0.4f,
              modLfoRate = 0.08f,
              modLfoDepth = 0.4f,
              modLfoShape = 0.3f,
              modLfoCoupling = 0.5f,
              holdProbability = 0.85f,
              holdLengthMin = 4,
              holdLengthMax = 12,
              delaySend = 0.7f,
              reverbSend = 0.8f,
              noteRangeLow = 54,
              noteRangeHigh = 78,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.6f,
              lpgMode = LpgMode.SUSTAINED,
              lpgDecay = 0.8f,
              lpgColour = 0.3f,
              pinHarmonics = true,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.05f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.02f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.FIXED,
              lickMode = LickMode.Fill,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.1f,
            density = 0.15f,
            envelopeProfile = EnvelopeProfile.DRONE,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.6f,
                max = 0.95f,
              ),
              energyDensity = MacroTarget(
                min = 0.08f,
                max = 0.3f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.0f,
              ),
              complexityVariation = MacroTarget(
                min = 0.05f,
                max = 0.2f,
              ),
              spaceDecay = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.3f,
                max = 0.6f,
              ),
              moodTimbre = MacroTarget(
                min = 0.35f,
                max = 0.7f,
              ),
            ),
            barStrategy = BarStrategy.MUTATE,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = PitchEvolution.Contour(
                driftRange = 0.1f,
              ),
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.STR,
              volume = 0.62f,
              harmonics = 0.45f,
              timbre = 0.35f,
              morph = 0.2f,
              modLfoRate = 0.02f,
              modLfoDepth = 0.3f,
              modLfoShape = 0.2f,
              modLfoCoupling = 0.3f,
              holdProbability = 0.95f,
              holdLengthMin = 16,
              holdLengthMax = 32,
              delaySend = 0.4f,
              reverbSend = 0.75f,
              noteRangeLow = 43,
              noteRangeHigh = 60,
              reverbBrightness = 0.4f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.STR,
              volume = 0.62f,
              harmonics = 0.45f,
              timbre = 0.35f,
              morph = 0.2f,
              modLfoRate = 0.02f,
              modLfoDepth = 0.3f,
              modLfoShape = 0.2f,
              modLfoCoupling = 0.3f,
              holdProbability = 0.95f,
              holdLengthMin = 16,
              holdLengthMax = 32,
              delaySend = 0.4f,
              reverbSend = 0.75f,
              noteRangeLow = 43,
              noteRangeHigh = 60,
              reverbBrightness = 0.4f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.ROOT_ONLY,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = 0.2f,
            density = 0.08f,
            envelopeProfile = EnvelopeProfile.DRONE,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.5f,
                max = 0.85f,
              ),
              energyDensity = MacroTarget(
                min = 0.05f,
                max = 0.15f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.0f,
              ),
              complexityVariation = MacroTarget(
                min = 0.0f,
                max = 0.1f,
              ),
              spaceDecay = MacroTarget(
                min = 0.2f,
                max = 0.2f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.4f,
                max = 0.4f,
              ),
              moodTimbre = MacroTarget(
                min = 0.35f,
                max = 0.35f,
              ),
            ),
            barStrategy = BarStrategy.INDEPENDENT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
          TrackVoice(
            engineEdm = OrpheusEngine(
              engineId = OrpheusEngineId.SWM,
              volume = 0.55f,
              harmonics = 0.65f,
              timbre = 0.45f,
              morph = 0.75f,
              modLfoRate = 0.04f,
              modLfoDepth = 0.4f,
              modLfoShape = 0.4f,
              modLfoCoupling = 0.4f,
              holdProbability = 0.6f,
              holdLengthMin = 6,
              holdLengthMax = 12,
              delaySend = 0.55f,
              reverbSend = 0.85f,
              noteRangeLow = 50,
              noteRangeHigh = 72,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            engineSpace = OrpheusEngine(
              engineId = OrpheusEngineId.SWM,
              volume = 0.55f,
              harmonics = 0.65f,
              timbre = 0.45f,
              morph = 0.75f,
              modLfoRate = 0.04f,
              modLfoDepth = 0.4f,
              modLfoShape = 0.4f,
              modLfoCoupling = 0.4f,
              holdProbability = 0.6f,
              holdLengthMin = 6,
              holdLengthMax = 12,
              delaySend = 0.55f,
              reverbSend = 0.85f,
              noteRangeLow = 50,
              noteRangeHigh = 72,
              reverbBrightness = 0.55f,
              delayFeedback = null,
              glideRate = 0.0f,
              lpgMode = LpgMode.ENGINE_DEFAULT,
              lpgDecay = 0.5f,
              lpgColour = 0.5f,
              pinHarmonics = false,
              pinTimbre = false,
              pinMorph = false,
              harmonicsModulation = 0.0f,
              harmonicsMacroSource = MacroSource.MOOD,
              harmonicsMacroRange = 0.0f,
            ),
            role = TrackRole.Melodic(
              chordFollow = ChordFollow.FOLLOW,
              lickMode = LickMode.None,
              lickDegreeOffset = 0,
              wahLick = false,
              wahParams = null,
              lickSource = LickSource.LEAD,
            ),
            pan = -0.4f,
            density = 0.12f,
            envelopeProfile = EnvelopeProfile.WILD,
            macroMap = TrackMacroMap(
              energyVolume = MacroTarget(
                min = 0.3f,
                max = 0.65f,
              ),
              energyDensity = MacroTarget(
                min = 0.05f,
                max = 0.25f,
              ),
              complexitySwing = MacroTarget(
                min = 0.0f,
                max = 0.2f,
              ),
              complexityVariation = MacroTarget(
                min = 0.1f,
                max = 0.4f,
              ),
              spaceDecay = MacroTarget(
                min = 0.4f,
                max = 0.8f,
              ),
              moodHarmonics = MacroTarget(
                min = 0.4f,
                max = 0.75f,
              ),
              moodTimbre = MacroTarget(
                min = 0.3f,
                max = 0.65f,
              ),
            ),
            barStrategy = BarStrategy.INDEPENDENT,
            evolutionWeight = -1.0f,
            soloBehavior = null,
            duckingProfile = null,
            evolution = Evolution(
              rhythmic = null,
              pitch = null,
            ),
          ),
        ),
        lick = Lick(
          steps = listOf(
            LickStep(
              scaleDegree = 4,
              duration = 4.0f,
              velocity = 0.65f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 2.0f,
              velocity = 0.6f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 5,
              duration = 4.0f,
              velocity = 0.7f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 4.0f,
              velocity = 0.65f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 0,
              duration = 4.0f,
              velocity = 0.7f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 6,
              duration = 8.0f,
              velocity = 0.6f,
              glideRate = 0.7f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 4.0f,
              velocity = 0.65f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 2.0f,
              velocity = 0.6f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 5,
              duration = 4.0f,
              velocity = 0.7f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 4,
              duration = 4.0f,
              velocity = 0.65f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 1,
              duration = 4.0f,
              velocity = 0.7f,
              glideRate = 0.6f,
            ),
            LickStep(
              scaleDegree = 0,
              duration = 8.0f,
              velocity = 0.6f,
              glideRate = 0.7f,
            ),
          ),
          loopLength = 48,
        ),
        lickMutation = 0.05f,
        lickOctave = 4,
        lickRotation = null,
        bassLine = null,
        bassLineMutation = 0.5f,
        bassLineOctave = -1,
        band = Band(
          members = listOf(
            BandMember(
              name = "Rhythm",
              tracks = listOf(
                0,
                1,
                2,
              ),
              alwaysActive = true,
              loudness = 0.3f,
              creativity = 0.3f,
              swing = 0.0f,
              drag = 0.0f,
            ),
            BandMember(
              name = "Bassist",
              tracks = listOf(
                3,
              ),
              alwaysActive = true,
              loudness = 0.6f,
              creativity = 0.2f,
              swing = 0.0f,
              drag = 0.0f,
            ),
            BandMember(
              name = "Keys",
              tracks = listOf(
                4,
                5,
              ),
              alwaysActive = true,
              loudness = 0.75f,
              creativity = 0.4f,
              swing = 0.0f,
              drag = 0.0f,
            ),
            BandMember(
              name = "Textures",
              tracks = listOf(
                6,
                7,
              ),
              alwaysActive = true,
              loudness = 0.5f,
              creativity = 0.5f,
              swing = 0.0f,
              drag = 0.0f,
            ),
          ),
          handoffMatrix = listOf(
            0.0f,
            0.2f,
            0.55f,
            0.25f,
            0.15f,
            0.0f,
            0.55f,
            0.3f,
            0.1f,
            0.1f,
            0.0f,
            0.8f,
            0.1f,
            0.1f,
            0.8f,
            0.0f,
          ),
          pullInMatrix = listOf(
            0.0f,
            0.2f,
            0.5f,
            0.3f,
            0.15f,
            0.0f,
            0.55f,
            0.3f,
            0.1f,
            0.15f,
            0.0f,
            0.75f,
            0.1f,
            0.15f,
            0.75f,
            0.0f,
          ),
          pullInBarsMin = 4,
          pullInBarsMax = 8,
          barsPerLeadMin = 8,
          barsPerLeadMax = 16,
        ),
        seed = 108,
        bpm = 50.0f,
        envelopeType = EnvelopeType.TIDES,
        rootNote = RootNote.G,
        scaleType = ScaleType.MAJOR,
        genre = GenreProfile(
          swingAmount = 0.0f,
          ghostProbability = 0.1f,
          noteRangeLow = 36,
          noteRangeHigh = 84,
          rhythmDensity = 0.0f,
          progressionStyle = ProgressionStyle.DRONE,
          chordsPerBar = 1,
          chordTransitionMatrix = null,
          customProgression = listOf(
            ChordStep(
              degree = 0,
              glideRate = 0.5f,
            ),
          ),
        ),
        energy = 0.3f,
        complexity = 0.2f,
        space = 0.95f,
        mood = 0.6f,
        deep = 0.8f,
        stepCount = 32,
        tension = TensionProfile(
          innerBars = 8,
          outerBars = 32,
          outerDepth = 0.5f,
          volume = 0.3f,
          tonal = TonalTension(
            octaveShift = false,
            keyShift = 0,
            halfLick = HalfLick.OFF,
            chromaticPassing = 0.0f,
          ),
          timing = 0.01f,
          evolution = EvolutionTension(
            timbreLow = 0.15f,
            timbreHigh = 0.45f,
            timbreProbability = 0.5f,
            morphLow = 0.1f,
            morphHigh = 0.5f,
            morphProbability = 0.4f,
            harmonicsLow = 0.15f,
            harmonicsHigh = 0.45f,
            harmonicsProbability = 0.3f,
            attackPoint = 0.25f,
            releaseSpeed = 0.8f,
          ),
          spurtChance = 0.0f,
        ),
        arrangement = Arrangement(
          sections = listOf(
            Section(
              name = "initiation",
              barsMin = 8,
              barsMax = 16,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 1,
                  weight = 1.0f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.4f,
              macroOverrides = MacroOverrides(
                energy = 0.3f,
                complexity = 0.2f,
                space = 1.2f,
                mood = 0.7f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = null,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "bloom",
              barsMin = 16,
              barsMax = 32,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 2,
                  weight = 0.7f,
                  transitionBars = 0,
                ),
                SectionTransition(
                  targetIndex = 0,
                  weight = 0.3f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.5f,
                complexity = 0.4f,
                space = 1.0f,
                mood = 0.8f,
              ),
              tensionOverride = null,
              soloMode = SoloMode.LickBuilder(
                probability = 0.4f,
                mutationRate = 0.2f,
              ),
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = null,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
            Section(
              name = "drift",
              barsMin = 12,
              barsMax = 24,
              barStep = 1,
              transitions = listOf(
                SectionTransition(
                  targetIndex = 1,
                  weight = 1.0f,
                  transitionBars = 0,
                ),
              ),
              recencyDecay = 0.5f,
              macroOverrides = MacroOverrides(
                energy = 0.25f,
                complexity = 0.5f,
                space = 1.3f,
                mood = 1.0f,
              ),
              tensionOverride = null,
              soloMode = null,
              trackOverrides = null,
              compingStyle = null,
              compingInversion = null,
              compingHumanization = null,
              chordFollow = null,
              customProgression = null,
              chordsPerBar = null,
              bpmMultiplier = 1.0f,
              bpmRampBars = 0,
              jamCarry = false,
            ),
          ),
          introIndex = 0,
          outroIndex = 2,
          defaultSectionBars = 16,
          lengthSeconds = 240..400,
          transitionOut = null,
        ),
        progressionAnchor = ProgressionAnchor.EVERY_8,
        progressionDriftRange = 0.05f,
        effects = VibeEffects(
          delayTimeA = 0.5f,
          delayTimeB = 0.75f,
          delayFeedback = 0.7f,
          delayDamping = 0.4f,
          reverbSize = 0.95f,
          reverbDamping = 0.35f,
          reverbBrightness = 0.55f,
          deepFloor = 0.5f,
        ),
        lickWah = null,
        anomalies = listOf(
          VoidAnomaly(
            probability = 0.02f,
            floorLevel = 0.25f,
            rampDownBars = 4.0f,
            floorBarsMin = 2.0f,
            floorBarsMax = 4.0f,
            rampUpBars = 2.0f,
            ghostIntensity = 0.3f,
          ),
        ),
      )
      }
}
