package org.balch.orpheus.features.pulsar.vibes

import org.balch.orpheus.features.pulsar.models.VibeName

/**
 * Every built-in vibe's name, which its provider and the catalogs use.
 * Add one here with a new vibe.
 */
object VibeNames {
    val AETHER_NATALIS = VibeName("Aether Natalis")
    val ARMY_STOMP = VibeName("Army Stomp")
    val ASCENDING_BLITZ = VibeName("Ascending Blitz")
    val BELL_TOLLS = VibeName("Bell Tolls")
    val BLACK_CAT = VibeName("Black Cat")
    val BLACK_CAT_OG = VibeName("Black Cat OG")
    val BLACKTOP_BOOGIE = VibeName("Blacktop Boogie")
    val BLUES_BURN = VibeName("Blues Burn")
    val BRICKLAYERS_LAMENT = VibeName("Bricklayer's Lament")
    val COMP_BLUES = VibeName("Comp Blues")
    val COMP_FUNK = VibeName("Comp Funk")
    val COMP_GOSPEL = VibeName("Comp Gospel")
    val COMP_JAZZ = VibeName("Comp Jazz")
    val COMP_PAD = VibeName("Comp Pad")
    val COMP_REGGAE = VibeName("Comp Reggae")
    val COMP_ROCK = VibeName("Comp Rock")
    val COMP_SKA = VibeName("Comp Ska")
    val CORNER_OFFICE = VibeName("Corner Office")
    val CORNER_OFFICE_OG = VibeName("Corner Office OG")
    val COSMIC_TECHNO = VibeName("Cosmic Techno")
    val DARK_BLITZ = VibeName("Dark Blitz")
    val DEEP_SPACE = VibeName("Deep Space")
    val DOG_HOUSE = VibeName("Dog House")
    val DOUBLE_SHIFT = VibeName("Double Shift")
    val DUST_GROOVE = VibeName("Dust Groove")
    val FILTER_FUNK = VibeName("Filter Funk")
    val FIRE_SKY = VibeName("Fire Sky")
    val FIRE_SKY_05F = VibeName("Fire Sky .5f")
    val FIRE_SKY_CX = VibeName("Fire Sky CX")
    val FIRE_SKY_OG = VibeName("Fire Sky OG")
    val FLOOR_BLITZ = VibeName("Floor Blitz")
    val GARAGE_BLITZ = VibeName("Garage Blitz")
    val JAZZ_BLITZ = VibeName("Jazz Blitz")
    val JUPITER = VibeName("Jupiter, the Bringer of Jollity")
    val KALEIDOSCOPE_DRIFT = VibeName("Kaleidoscope Drift")
    val LOST_IN_SPACE = VibeName("Lost In Space")
    val MELLOW_HAZE = VibeName("Mellow Haze")
    val MOD_PIONEER = VibeName("Mod Pioneer")
    val NATALIS_SHIMMER = VibeName("Natalis Shimmer")
    val ODYSSEUS_LORE = VibeName("Odysseus Lore")
    val OUROBOROS_BLOOM = VibeName("Ouroboros Bloom")
    val RUST_BELT = VibeName("Rust Belt")
    val RUST_BELT_OG = VibeName("Rust Belt OG")
    val SIXTIES_REBEL = VibeName("Sixties Rebel")
    val SPACE_AND_DRUMS = VibeName("Space & Drums")
    val STAY_ASLEEP = VibeName("Stay Asleep")
    val SWAMP_SWAGGER = VibeName("Swamp Swagger")
    val SYMPHONY_NO_5 = VibeName("Symphony No. 5 in C Minor")
    val TECHNO_WOBBLE = VibeName("Techno Wobble")
    val TIME_ZONE = VibeName("TimeZone")
    val TREMOLO_TIDE = VibeName("Tremolo Tide")
    val UTC = VibeName("UTC")
    val VANISHED_SKYLINE = VibeName("Vanished Skyline")
    val VELVET_LEASH = VibeName("Velvet Leash")
    val VOLTAGE_STRUT = VibeName("Voltage Strut")
}
